### ISSUE TITLE
Version update PRs warn about not being able to find old version in tags

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#1015]
## Bug description

When khebut creates a PR to address a "new version" request from an issue, sometimes (?) it adds a warning note ([this one](https://github.com/thoth-station/kebechet/blob/67c7364d46901306b15b6bd4531c49e8639e3e43/kebechet/managers/version/messages.py#L20)) saying:

> The release version mentioned in the source-code couldn't be found in git tags, hence the release is created from the start.

However:
- the previous version tag does exist
- the existing code references that version

Also, the contents of the PR look correct: they correctly update the version in the code, and they generate a changelog that matches the diff from the previous tag.

So, it seems that this warning note appears when it should not. This causes confusion

### Steps to Reproduce
1. Create a "New minor version" or "New patch version" issue (observed on these two so far)
2. Wait for kebechet to create the PR for the version update
3. Notice the warning in the PR description

### Actual behavior

Examples:
- https://github.com/thoth-station/user-api/pull/1694
- https://github.com/AICoE/aicoe-ci/pull/168

### Expected behavior

No warning note, unless it is necessary.

If it actually is necessary, then maybe an improved message to help understand what's missing/wrong.

### Environment information

This is Kebechet v1.7.3 AFAICT

(side note: maybe we could add kebechet version information in the messages it generates, to help in issue reporting)

**Comment by codificat** [comment]
This keeps happening, e.g. https://github.com/thoth-station/user-api/pull/1725

/triage accepted
/priority important-soon

**Comment by KPostOffice** [comment]
I believe this was fixed by https://github.com/thoth-station/kebechet/pull/995/files

**Comment by KPostOffice** [comment]
There was no release until Mar 14 after this PR was made. I will close this. Please reopen if you see this again.
