### ISSUE TITLE
[EPIC] Tracking issues blocking Kebechet advise manager integration

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/kebechet#1029]
This is an issue for tracking bugs associated with advise manager as we move towards thoth mvp. Please link any issues or PRs which are relevant to this effort.

## Acceptance criteria
- [x] successfully receive thoth-advise PR in `thoth-python`

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/support/issues/181

**Comment by codificat** [comment]
I think https://github.com/thoth-station/kebechet/issues/1029 should also be addressed in the context of this epic

**Comment by codificat** [comment]
It seems that Kebechet can now successfully provide advice to the `python` repository: https://github.com/thoth-station/python/issues/479

This seems to work now, so
/close
