### ISSUE TITLE
Kebechet manual update request did not update new available dependency

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#1039]
## Bug description
Related issue https://github.com/thoth-station/mi-scheduler/issues/227

Tried to update new `thoth-common` dependency (https://github.com/thoth-station/common/issues/1256 ) by manually requesting kebechet, 

### Actual behavior
Request did not recognize new available dependency and was not successful (khebhut referenced previous release commit and closed the issue) 

### Expected behavior
Update new available `common` dependency to `0.36.2`

**Comment by KPostOffice** [comment]
@xtuchyna Are you sure a release was available on PyPI before you requested an update?

**Comment by KPostOffice** [comment]
If not could you please create a new issue requesting an update?

**Comment by harshad16** [comment]
I verified the issue. It seems like just not connecting the right pr commit.

Opened a `kebechet update` issue https://github.com/thoth-station/mi-scheduler/issues/237, after the release of the new thoth-common v0.36.4 
there was an auto update pr https://github.com/thoth-station/mi-scheduler/pull/238 with the right changes.
however, the issue didn't tag it properly in the comments.
https://github.com/thoth-station/mi-scheduler/issues/237#issuecomment-1216725695

This issue should be a low priority as it doesn't block the work. 
/priority important-longterm

**Comment by harshad16** [comment]
/triage accepted

Assigning it to @shreekarSS

**Comment by KPostOffice** [comment]
Hmm, I think it is pointing to the intended commit. It is not meant to point to the merge commit but rather the commit for which the manager was run on. What should happen is that the update issue is commented on with a reference to the opened PR.
