### ISSUE TITLE
Version manager failed to get the correct list of maintainers

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#1055]
## Bug description

Kebechet refused to act on a release request here:
https://github.com/thoth-station/thoth-github-action/issues/36#issuecomment-1142046322

saying "you are not stated in maintainers section for this project", and providing a list of "maintainers".

However:

- at this time, that project does not have an explicit list of maintainers in `.thoth.yaml`: https://github.com/thoth-station/thoth-github-action/blob/296b685aa45df9a9c18acc9aca240f27cb916d67/.thoth.yaml#L16
 
- kebechet is expected to get the list of maintainers from the approvers list in `OWNERS`: https://github.com/thoth-station/thoth-github-action/blob/296b685aa45df9a9c18acc9aca240f27cb916d67/OWNERS#L3

- the list of approvers above does not match the list of maintainers in kebechet's comment

### Expected behavior

The list of maintainers would be taken from the approvers list.

Also, in case Kebechet needs to add this comment ("Sorry but your are not stated in maintainers"), the comment should contain a link to where that list of maintainers is taken from, so the user can understand what's going on.

### Environment information

It might also be a good idea for Kebechet to mention its version/env info in the comments it generates, for debugging purposes.

**Comment by KPostOffice** [comment]
Looks similar to the problem fixed [here](https://github.com/thoth-station/kebechet/pull/1081), I don't think that it was fixed by this PR though.
