### ISSUE TITLE
[3pt] Include tag creation in kebechet with release option

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#1056]
## Problem statement
Kebechet provides a feature to help with the release, the templates for releases create a changelog and update the version file. However, once the pull request is merged, the new version tag is not created by kebechet. The tag has to be created by some other tool or the user themselves. It would be great if kebechet can monitor the release pull request is merged and creates a tag based on it.

## High-level Goals
- Create a tag on the merge of the release pull request created by kebechet.
- Explore and learn about kebechet.

## Proposal description
- monitor the pull request created by kebechet for the release issue and then create a tag.

## Acceptance Criteria

- [ ] Explore the [version manager](https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/version/version.py) codebase
- [ ]  Create a script to create a git tag based on the version update and push it to the repo
- [ ]  Explore kebechet code base on including script to run on merge of the release PR.
- [x] #1060
- [x] #1059

### Additional context
- Github webhook payload: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads
- Github create tags with API: https://docs.github.com/en/rest/git/tags

**Comment by codificat** [comment]
Thanks for creating the issue!
For additional context, this topic was discussed in the [Thoth Tech talk](https://bit.ly/thoth-tech-talk-sessions) on Mar 17, 2022 (search for "How many bots does it take to tag a release)

**Comment by harshad16** [comment]
Assigning this as good-first-issue
and stating story point to 3, as it require knowledge of github API, webhook and kebechet.
