### ISSUE TITLE
[1pt] Delete the branch if the pr is merged and tag is created.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#1059]
As a kebechet operator, I would like to have kebechet clean the branch once it has fulfilled its purpose so that it would make the repository maintainers' life easier.

**Acceptance criteria**
- [ ] Delete the branch if the pr is merged and the tag is created.
- [ ] Don't delete the branch if pr is pending or closed.

**Comment by harshad16** [comment]
@KPostOffice @Gkrumbach07 can please give your ack on this issue, if you feel this is an apt request.

**Comment by KPostOffice** [comment]
ack. This is doable and a usefule feature I think

**Comment by codificat** [comment]
#1065 addressed this, so 
/close
