### ISSUE TITLE
[2pt] Add signed-off-by in commit messages

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#1067]
## Problem statement

When Kebechet sends e.g. a PR to update dependencies, the commit message(s) do not contain a `Signed-off-by:` line.

This can prevent [DCO](https://developercertificate.org/) checks from working.

Example: https://github.com/os-climate/data-platform-demo/pull/41/checks?check_run_id=6642425305

## High-level Goals

To have all of Kebechet's commits `Signed-off-by` the bot.

## Acceptance Criteria

- [ ] for every commit that Kebechet generates, the commit message always includes a line `Signed-off-by: Kebechet <kebechet-s@email.example.com>`

**Comment by Gkrumbach07** [comment]
**story points** 2
