### ISSUE TITLE
[3pt] Advise manager starting multiple advice requests and not closing them

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#1069]
## Bug description

I requested an advice from Kebechet in https://github.com/thoth-station/ps-ip/issues/19 and it started 2 advise requests simultaneously.

Both of them completed without error.

Apparently, nothing else happened, and the issue is still open.

### Steps to Reproduce
1. Have advise manager configured on your repo (e.g. https://github.com/thoth-station/ps-ip/blob/7fade66947eea249534c52f3789b560bd480bab4/.thoth.yaml#L22-L24)
2. Create an issue on the repo, with title: *Kebechet Advise*
3. Wait for the bot to act

### Actual behavior

- 2 advice requests started, as per comments in the issue by the bot
- issue still open, with no indication of what happened to the requested advice

### Expected behavior

- only 1 advice request started
- issue gets updated with the result of the advice

### Environment information

Side note: it might be good if Kebechet would report its version on the comments it generates.

It seems to be Kebechet `v1.9.0`: https://github.com/thoth-station/thoth-application/blob/aff38154c66efe09b1b25084e12083c04029a00a/kebechet/overlays/aws-prod/imagestreamtag.yaml#L11

**Comment by Gkrumbach07** [comment]
related: https://github.com/thoth-station/ps-nlp/issues/151
**story points** 3

**Comment by shreekarSS** [comment]
Related https://github.com/thoth-station/support/issues/264#event-7066575424

**Comment by shreekarSS** [comment]
Related https://github.com/thoth-station/support/issues/266

**Comment by shreekarSS** [comment]
Feature request for Kebechet to report it's version https://github.com/thoth-station/kebechet/issues/1099
