### ISSUE TITLE
Logs leak access token

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#1123]
## Bug description

When looking at the logs of a kebechet workflow run, I noticed this towards the beginning:

```
2022-08-31 11:21:58,404   1 INFO     kebechet.utils:59: Cloning repository https://username:token@github.com/thoth-station/s2i-minimal-notebook to .
```

### Steps to Reproduce
1. Trigger an action that results in a Kebechet manager cloning a repo
2. Look at the logs of the resulting workflow execution
3. Find the gh access token in the logs

### Actual behavior

Logs include access credentials in plain text

### Expected behavior

No credentials are leaked to the logs

### Environment information

Kebechet v1.10.3

### Additional context

The offending line is: https://github.com/thoth-station/kebechet/blob/c864a6babfa2727392dd62b56915739cc3c5b051/kebechet/utils.py#L59

**Comment by harshad16** [comment]
About regenerating the token, the github app token for installation expire in 8 hours
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation#user-token-revoked-due-to-github-app-configuration
