### ISSUE TITLE
investigate why Kebechet is not updating, and make it update (... s2i-minimal)

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#1127]
can we make kebechet update https://github.com/thoth-station/s2i-minimal-notebook/ ?

dependabot is pretty active on it, https://github.com/thoth-station/s2i-minimal-notebook/pulls so should kebechet!

/kind feature

**Comment by codificat** [comment]
I believe this is a duplicate of #1122 - there's some detail there on why kebechet is not currently able to update the s2i-minimal-notebook repo.

/triage duplicate
/close
