### ISSUE TITLE
[1pt] kebechet fail close the dependency update issue if there is no changes needed

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#1145]
## Bug description
If all the dependencies are up-to-date in a repo, and developer triggers kebechet-update.
the service would fail to close the issue with relevant comment.
Due to following issue:
```
kebechet:219: An error occurred during run of manager {'configuration': {'labels': ['bot']}} <class 'kebechet.managers.update.update.UpdateManager'> for 'thoth-station/graph-backup-job', skipping
Traceback (most recent call last):
  File "/home/user/kebechet/kebechet_runners.py", line 217, in run
    instance.run(**manager_configuration)
  File "/home/user/kebechet/managers/update/update.py", line 930, in run
    pr=self._pr_list[0],
IndexError: list index out of range
```

### Steps to Reproduce
1. Go to any repo with up-to-date dependencies 
2. Click on  issue and create `kebechet update` request.
3. wait for the process no action would be done.

### Actual behavior
no action on the issue.

### Expected behavior
closes issue with previous pr that was from kebechet 

### Environment information
Kebechet: v1.10.5

### Additional context

Happened on:
https://github.com/thoth-station/package-releases-job/issues/661
https://github.com/thoth-station/cve-update-job/issues/485
https://github.com/thoth-station/adviser/issues/2385
https://github.com/thoth-station/graph-backup-job/issues/245

each of there logs are included in them.

**Comment by KPostOffice** [comment]
Need to add a check at update.py L925 checking if the PR list is empty. If it is close the issue with a comment indicating that no updates are necessary.
