### ISSUE TITLE
Provide git commit hashes in changelog entries

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#150]
**Is your feature request related to a problem? Please describe.**

I would like to be pointed directly to commit/pull request that introduced the given feature stated in the generated changelog - see for example https://github.com/thoth-station/common/pull/90 (hashes are missing there).

**Describe the solution you'd like**

Add hashes to the listing so that a user can directly go to change/pull request that introduced the given feature/fix.

**Comment by goern** [comment]
@fridex is this still relevant?

**Comment by fridex** [comment]
Yes, we might also improve output a bit so the links are clickable can can direct users to the PRs/commits.

**Comment by codificat** [comment]
> Rotten issues close after 30d of inactivity.

Bug in the bot (already fixed) - the issue was not rotten at the time.

/reopen
/remove-lifecycle rotten

**Comment by codificat** [comment]
Implemented in #1001 (made a typo in the PR description that prevented automatic closure)
/close
