### ISSUE TITLE
Monitor Kebechet and report an issue if the jobs was not run for a certain period of time

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#177]
**Is your feature request related to a problem? Please describe.**

With recent registry issues where images were removed from registry, kebeched job was crash-looping due to image pull errors.

**Describe the solution you'd like**

We should set up a monitoring to make sure Kebechet runs. If Kebechet does not run for a certain period of time, we should be notified so we know the job is not running.

**Comment by saisankargochhayat** [comment]
@fridex Should we keep this open?

**Comment by fridex** [comment]
Let's close it :+1:
