### ISSUE TITLE
No need to replicate old environment if there is updated only one package

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#182]
If there is updated only one package in the update manager, there is no need to replicate old environment for incremental update. The current environment is has already correctly computed Pipfile.lock.

**Comment by fridex** [comment]
(Optimization... )

**Comment by goern** [comment]
is this still relevant?

**Comment by fridex** [comment]
Yes for the current implementation, but we should not invest time into this.

**Comment by goern** [comment]
/assign @KPostOffice 
please have a look if we can close this with the new implementation. thx.

**Comment by KPostOffice** [comment]
@goern I'm not sure what "new implementation" you are talking about

**Comment by goern** [comment]
@fridex is this still a valid RFE?

**Comment by fridex** [comment]
This is no longer relevant. Sai had to change the update logic not to work on incremental updates (one PR per update) because of pipenv issues. This optimization was for the old incremental updates logic.

Moreover, by switching to advise based updates, we will not use pipenv at all.

/close
