### ISSUE TITLE
The bot strips environment markers

### ISSUE THREAD

**Issue by TomasTomecek** [thoth-station/kebechet#188]
**Describe the bug**
The bot proposed a change recently and removed environment markers from req.txt:

```diff
-enum34==1.1.6 ; python_version <= '2.7'
+enum34==1.1.6
```

This essentially broke our software b/c enum34 was suddenly a hard req for python 3.

https://github.com/user-cont/conu/pull/321/files#diff-b4ef698db8ca845e5845c4618278f29aL13

Edit: I was probably blind when I wrote the first sentence

**Comment by fridex** [comment]
@TomasTomecek thanks, makes sense
