### ISSUE TITLE
it seems that the bot gets triggered on CI being complete

### ISSUE THREAD

**Issue by TomasTomecek** [thoth-station/kebechet#189]
This is the scenario:
1. The bot opens a PR with updates.
2. The CI is triggered.
3. CI completes.
4. CI status is updated in the PR
5. Bots force-pushes to the branch -- new commit, no changes.
6. The CI is triggered.
and so on...

I hope it's clear to see that this makes the CI to go forever.

Examples:
https://ci.centos.org/job/user-cont-conu-pr/1309/
https://ci.centos.org/job/user-cont-conu-pr/1308/
https://ci.centos.org/job/user-cont-conu-pr/1307/
https://ci.centos.org/job/user-cont-conu-pr/1306/
https://ci.centos.org/job/user-cont-conu-pr/1305/
https://ci.centos.org/job/user-cont-conu-pr/1304/

**Comment by TomasTomecek** [comment]
The CI system reports results back to the pull request via github API by updating status of commit:

https://developer.github.com/v3/repos/statuses/

**Comment by goern** [comment]
Newer CI systems might also use https://developer.github.com/v3/checks/ rather than statuses

**Comment by fridex** [comment]
> The CI system reports results back to the pull request via github API by updating status of commit:

Kebechet's implementation should take this into account, it basically works purely on Git level.

**Comment by TomasTomecek** [comment]
So please explain the behaviour then :D

**Comment by fridex** [comment]
> So please explain the behaviour then :D

I tried to dig into it, but we do not have logs for these runs :( I suspect there is some logical error... this time Tomas saved us from AI (not OOM yet :) ).

I will try to check it once again.

**Comment by TomasTomecek** [comment]
Any updates?

**Comment by fridex** [comment]
> Any updates?

Not yet :( How urgent is it?

**Comment by TomasTomecek** [comment]
Not urgent at all, we can revert back to the former dependency management without pinning to specific versions; we were just debating the current situation, see the linked issue above.
