### ISSUE TITLE
Check before force pushing into master

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#195]
As per comments, we force-push each time there is an update. We should first check if the current master is base for the PR. If not, perform force pushing only in that case (otherwise leave pull-request untouched).

This causes issues stated in https://github.com/thoth-station/kebechet/issues/189

https://github.com/thoth-station/kebechet/blob/49a8fedcf0b70a2010e5942275a951cf4855e103/kebechet/managers/update/update.py#L218-L221

**Comment by goern** [comment]
@fridex is this still valid?

**Comment by fridex** [comment]
This logic should be soon replaced with thoth based update manager. I would keep it for now here and let's see if we'll experience the same issue with thoth based update manager.

CC @KPostOffice

**Comment by KPostOffice** [comment]
@fridex From what I understand. we are creating a branch from master, then updating files and then force pushing to a branch which already exists, when the push occurs the CI pipeline is triggered causing Kebechet to create a new local branch from master and force push it on top of the previous changes even though the changes are the exact same. This cycle repeats forever.

**Comment by fridex** [comment]
Yes, that's correct 👍🏻 That is not good behavior - Kebechet should push only if any changes are made (otherwise that CI pipeline trigger is happening in a loop).

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/kebechet/blob/49a8fedcf0b70a2010e5942275a951cf4855e103/kebechet/managers/update/update.py#L252-L260

@fridex Would this check be sufficient?

**Comment by fridex** [comment]
Not sure about it. Commit SHA will not match even if the content of the commit content is the same.

**Comment by KPostOffice** [comment]
because the # of commits on top of master is only 1, we could just check and see if the currently open PR commit history ends with master/HEAD commit + a single commit which is the change being made.

**Comment by fridex** [comment]
That would work if there aren't any new commits in the current master. But what if the update has newer packages than the already opened pull request?

**Comment by KPostOffice** [comment]
We could check the current version installed. If the PR is attempting to install a package whose version is less than the one specified in Pipfile.lock, then we just close the PR which is open.

**Comment by goern** [comment]
@KPostOffice are you actively working on this? if so, please put some labels on it. thx!

**Comment by fridex** [comment]
I'm not sure if this is a priority now - with the Thoth based update manager this will not be needed. It might be better to invest into the Thoth based update manager to deliver a long-term solution.
