### ISSUE TITLE
Add support for managing lock files in nested directories

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#20]
As a user of Kebechet I would like to make sure Kebechet also manages nested ``Pipfile.lock`` and ``requirements.txt`` files. This can be accomplished either by searching for files matching the given filename or explicitly by stating files to be monitored in the configuration file (the latter is preferred for us).

**Comment by goern** [comment]
@fridex is this stil relevant?

**Comment by fridex** [comment]
No longer required, we use overlays.
