### ISSUE TITLE
Kebechet does not recognize release candidates

### ISSUE THREAD

**Issue by CermakM** [thoth-station/kebechet#228]
**Describe the bug**
`New minor release` issue bumps up release candidate `0.3.0-rc0` to `0.4.0`

**Expected behaviour**
Release candidate version is updated to the relevant release, in this case, `0.3.0`

**Additional context**
https://github.com/CermakM/jupyter-datatables/pull/13/files

**Comment by CermakM** [comment]
@fridex This is not really a bug in Kebechet, I'd say we're missing a proper definition of `New minor release` .. [semver](https://pypi.org/project/semver/) while bumping the `minor` version disregards the release candidate part. Turning release candidate into a * release is called `finalization` in semver terminology.

So there are two possible solutions, either

**A)** we check for pre-release part in the version specifier on every `New * release` issue or
**B)** we create a new command, proposal: `Finalize version`

The equivalent to the B) in `semver` package is `finalize_version` and works as follows:
```python
finalize_version("0.3.0-rc.1")  # 0.3.0
finalize_version("1.0.0-rc.1")  # 1.0.0
finalize_version("1.3.0-rc.1")  # 1.3.0
```

I'd vote for **B**, WDYT?

**Comment by fridex** [comment]
Nice! I would go with B as you propose. Using `New * release` on a release candidate would be an invalid operation (as the version should be finalized first). Ack?

**Comment by CermakM** [comment]
Ack.
