### ISSUE TITLE
replace IGitt with ogr

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#250]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
IGitt should be migrated to https://github.com/packit-service/ogr

**Describe alternatives you've considered**
a) keep the constantly outdating IGitt
b) invest in keeping IGitt up to date

**Additional context**
problems with IGitt's dependencies 
https://github.com/AICoE/sesheta/issues/38

Related: #206

**Comment by CermakM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(?) Replace IGitt with ogr](https://trello.com/c/RoVzlnAW/799-replace-igitt-with-ogr)

**Comment by saisankargochhayat** [comment]
Is this issue still relevant?
