### ISSUE TITLE
Fail in version manager if no changes were made

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#254]
**Describe the bug**

Kebechet's version manager always releases new packages when a specific issue is opened. It would be great to fail if there are no changes between releases so we do not bump new version without any specific reason (no changes in the source code).

**To Reproduce**

https://github.com/thoth-station/common/pull/505

**Expected behavior**

Kebechet would close the issue and comment about no changes detected between the two releases.

**Comment by saisankargochhayat** [comment]
@fridex Would it be a good idea just to add a check to if `_compute_changelog` returns an empty list, just close the issue stating no changes between the two releases?

**Comment by fridex** [comment]
> @fridex Would it be a good idea just to add a check to if `_compute_changelog` returns an empty list, just close the issue stating no changes between the two releases?

Yes! That sounds like a good approach :+1:
