### ISSUE TITLE
Version matching in version manager produces wrong changelog if version is touched by user

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#277]
**Describe the bug**

If a user manually touches version string in sources, there is no version tag created in the git. That means the version manager cannot find a tag from which the changelog should be computed and thus creates a changelog from the first commit (the whole git history).

**To Reproduce**
1. Create a new release manually
2. Issue a new release using Kebechet
3. Kebechet opens a PR with CHANGELOG computed

**Expected behavior**

As Kebechet uses git tags to spot the previous release and matches it with the one found in sources, Kebechet should at least warn there were some releases issued but no tag was found in the history.

As Kebechet works now on an incremental flat git history, we could also consider extending Kebechet functionality to support pre-releases (where a final release changelog would be computed from pre-releases as well). In that case, the manipulation logic will need to be revisited.

**Comment by saisankargochhayat** [comment]
Related - https://github.com/thoth-station/kebechet/issues/581

**Comment by saisankargochhayat** [comment]
Closed with #628
