### ISSUE TITLE
Moving managers to .thoth.yaml in respective repositories. 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#293]
We would like to move the managers from `config/.thoth.yaml` to `.thoth.yaml` in their respective repositories, and just have the slug and KEBECHET_TOKEN in .thoth.yaml for now.

**Comment by fridex** [comment]
@saisankargochhayat I think the move is to `.thoth.yaml` in respositories not to use the `config/thoth.yaml` in this repository, right?

**Comment by saisankargochhayat** [comment]
Yes, that's right :) I think I described the issue a little wrong. So kebechet would just have slug names in .thoth.yaml for now right?

**Comment by fridex** [comment]
> Yes, that's right :) I think I described the issue a little wrong. 

OK, just to make sure we are on the same page :)

> So kebechet would just have slug names in .thoth.yaml for now right?

For now, that would be fine - its a first step. Later, it can be propagated from webhook to guarantee source. :+1:

**Comment by saisankargochhayat** [comment]
So I have reused some existing functions from the run-url method. I was wondering, what the thoth_demo.yaml would contain, like we need token, and slug obviously, maybe service_url isn't necessary?
Should I add another method to download just using slug and service_type? Right now this seems to be running on my sample repo with the `info` manager. [link](https://github.com/saisankargochhayat/kebechet_sample/issues/4)

**Comment by fridex** [comment]
> So I have reused some existing functions from the run-url method. I was wondering, what the thoth_demo.yaml would contain, like we need token, and slug obviously, maybe service_url isn't necessary?
> Should I add another method to download just using slug and service_type? Right now this seems to be running on my sample repo with the `info` manager. [link](https://github.com/saisankargochhayat/kebechet_sample/issues/4)

I think I answered this in https://github.com/thoth-station/kebechet/pull/294#discussion_r373006015 Let me know if you need more info

**Comment by saisankargochhayat** [comment]
@fridex Should I close this? Or do I need to move the AICOE config's to their repo's?

**Comment by fridex** [comment]
> @fridex Should I close this? Or do I need to move the AICOE config's to their repo's?

Up to you. Please adjust also AICoE repos.

**Comment by saisankargochhayat** [comment]
Moved all the AICoE configs to their repo's.
