### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#295]
Octomachinery requires Python 3.7+ as octomachinery relies on contextvars which doesn’t have a backport.
https://docs.octomachinery.dev/en/latest/getting-started.html#runtime-pre-requisites

**Comment by fridex** [comment]
AFAIK we don't have any bits that would prevent us from upgrading to Python3.7 (not sure about the libraries used). Worth to give it a try :)

You'll need to set Pipenv's Python to Python3.7:

```console
pipenv --python 3.7
```

https://github.com/thoth-station/kebechet/blob/7960cea54a2a59f03cc30a8ea00fc7260e6ca222/Pipfile#L30-L31

And adjust the container image to provide Python3.7 in Dockerfile. Using Fedora:31 could be just fine (it has Python3.7 by default).

**Comment by goern** [comment]
We have a py37 s2i Image, don’t we?

**Comment by fridex** [comment]
> We have a py37 s2i Image, don’t we?

Yes. unfortunately, kebechet is not an s2i application as of now. I don't recall why we were not able to create s2i app out of it.

**Comment by fridex** [comment]
> > We have a py37 s2i Image, don’t we?
> 
> Yes. unfortunately, kebechet is not an s2i application as of now. I don't recall why we were not able to create s2i app out of it.

But nothing prevents us to dig into it :)

**Comment by fridex** [comment]
> > > We have a py37 s2i Image, don’t we?
> > 
> > 
> > Yes. unfortunately, kebechet is not an s2i application as of now. I don't recall why we were not able to create s2i app out of it.
> 
> But nothing prevents us from digging into it :)

**Comment by saisankargochhayat** [comment]
Probably just switch to Python 3.8 directly.

**Comment by fridex** [comment]
> Probably just switch to Python 3.8 directly.

+1

**Comment by saisankargochhayat** [comment]
Completed with Kebechet v1.2.2
