### ISSUE TITLE
Make kebechet recieve the whole payload from a webhook.

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#296]
Kebechet would receive the whole webhook payload as a string, as the only argument.

**Comment by saisankargochhayat** [comment]
@fridex as @goern suggests, the cli might not accept the whole webhook as a string? I think cli can accept maximum 2097152 bytes as argument.

**Comment by fridex** [comment]
> @fridex as @goern suggests, the cli might not accept the whole webhook as a string? I think cli can accept maximum 2097152 bytes as argument.

We will strip it on the webhook side (or it can be mounted as a file into the container in the worst case if we really need all the info).

**Comment by saisankargochhayat** [comment]
I am able to pass a sample issue payload from the webhook for now, as a cli string.

**Comment by fridex** [comment]
> I am able to pass a sample issue payload from the webhook for now, as a cli string.

To make it compliant with the above, something like this should do the trick:

```python
if os.path.isfile(parameter):
    with open(parameter) as f:
        payload = json.load(f)
else:
    payload = json.loads(parameter)
```

**Comment by saisankargochhayat** [comment]
https://click.palletsprojects.com/en/7.x/arguments/
I think click has a way to read in flies as a argument?
