### ISSUE TITLE
pre approved PR?

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#3]
does https://github.com/thoth-station/kebechet/blob/7f374d07a733375d64efb43bf2d2f2c7150bffee/config/thoth.yaml#L4 mean that PR opened by kebechet are pre-approved? if so? they ignore any CI job result, I would consider that a bug :)

**Comment by goern** [comment]
sesheta will not wait, she just looks for the "approved" label, a human must take CI result into consideration if he /approves a PR.

**Comment by fridex** [comment]
A place for improvement? :)
