### ISSUE TITLE
Making manager's responsive to only particular event triggers.

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#300]
Manager's only react if the event trigger is relevant to them.

Manager | Github Event (event_type) | Gitlab Event (object_kind)
-- | -- | --
info | ‘issues’ | ‘issue’
pipfile_requirements | ‘push’ | ‘push’, ‘merge_request’
thoth_advise | ‘push’, ‘issues' | ‘push’, ‘issues', ‘merge_request’
thoth_provenance | ‘push’, ‘issues’ | ‘push’, ‘issue’, ‘merge_request’
update | ‘push’, ‘issues’ | ‘push’, ‘issue’, ‘merge_request’
version | ‘issue’ | ‘issue’

@fridex @goern

**Comment by saisankargochhayat** [comment]
Are we going to extract more info from the payload like what's the issue title or so? 
Because currently the managers themselves interact with the repo and do these operations, like 'info' looks for info in issue's.

**Comment by fridex** [comment]
> @fridex @goern
> Are we going to extract more info from the payload like what's the issue title or so?
> Because currently the managers themselves interact with the repo and do these operations, like 'info' looks for info in issue's.

Yes, definitely.

This is tightly bound with [1] - the logic behind managers' implementation should decide what to do based on the event. So instead of statically declare which manager should be run on which type, this information can be part of the managers logic.

[1] https://github.com/thoth-station/kebechet/pull/304/files

**Comment by saisankargochhayat** [comment]
That makes sense, I will pass the event type to the manager, and it would have it as a global variable, if it acts on this kind of event or not.

**Comment by saisankargochhayat** [comment]
Should be resolved with #304
