### ISSUE TITLE
Kebechet consuming Thamos advises

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#313]
Create a new Kebechet manager that applies thamos advises to a repository. As Qeb-Hwt does this on an informational level (as a Check to a GitHub Pull Request) Kebechet’s `thamos-manager` should do it in an active way by opening up a PR to “follow and advise”.

**Comment by KPostOffice** [comment]
take a look at thoth_advise manager

**Comment by saisankargochhayat** [comment]
As @KPostOffice, the functionality seems to the same what thamos-manager intends to be. However the it's not there in any of our repo's, and the endpoint doesn't seem to work for a sample repo I tried. 
Error log - https://paste.ofcode.org/Hqb9m4xQ3SWYXmG4KeYSDv

**Comment by fridex** [comment]
IMHO we should not create this logic for kebechet as it is now. We should re-use already existing workflow as done for GitHub notification and use argo workflows for this. In that case, the whole logic used in argo workflows will be reused; the only thing that will change is the "reporting" logic (and parameters supplied). As of now, there is a script that submits results to GitHub app, the reporting task can be replaced by a logic that opens a PR. The maintainability cost of this solution is lower as we reuse what we already use for github app.

From kebechet perspective - we can use the manager implemented together with "source management" abstraction to support github/gitlab/pagure/...

> Error log - https://paste.ofcode.org/Hqb9m4xQ3SWYXmG4KeYSDv

@saisankargochhayat Please report the issue so we can fix it. It looks like an issue on user api

**Comment by saisankargochhayat** [comment]
@fridex  the related issue - [Link](https://github.com/thoth-station/user-api/issues/799)

**Comment by saisankargochhayat** [comment]
Closing as tracked in #383
