### ISSUE TITLE
Adding OpenDataHub projects

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#326]
They seem to have so many repositories under one repository, how do we support it?
I dont think, we do support nested repo's. 
https://gitlab.com/opendatahub/ai-library/-/tree/master/flakes_train

CC - @fridex @harshad16

**Comment by fridex** [comment]
> They seem to have so many repositories under one repository, how do we support it?
> I dont think, we do support nested repo's.
> https://gitlab.com/opendatahub/ai-library/-/tree/master/flakes_train
> 
> CC - @fridex @harshad16

As discussed on the private chat, try kebechet on gitlab repos with the expected structure first. Also, try to reach out to ai library if they plan/are willing to restructure their s2i approach and what impact/investment would that be on their side. Are there any other repos we could support on odh side?

**Comment by harshad16** [comment]
Ah, that's right. They have component in nested repo's.
I haven't heard back from them regarding the other python project they have, if I get any response I will let you guys know.

**Comment by harshad16** [comment]
@saisankargochhayat I guess we can start with this https://gitlab.cee.redhat.com/data-hub/ai-ingest.

**Comment by saisankargochhayat** [comment]
I have requested them to add sesheta as a collaborator, let's hope they do that :)
https://gitlab.cee.redhat.com/data-hub/ai-ingest/issues/1

**Comment by saisankargochhayat** [comment]
We need to wait on this - https://github.com/packit-service/ogr/issues/354
Before we can support enterprise gitlab deployments.

**Comment by saisankargochhayat** [comment]
We need to need to wait till OGR supports enterprise deployments of gitlab.

**Comment by saisankargochhayat** [comment]
@fridex What certificate should we add when we deploy, would the cron-job, would the image have it and we just point it to it?
I think there is `GITLAB_KEBECHET_TOKEN` in job-kebechet-template.yaml, but where do we add, the `GITLABCEE_KEBECHET_TOKEN`?

**Comment by fridex** [comment]
> We need to need to wait till OGR supports enterprise deployments of gitlab.
> OGR works with gitlab.cee if we do -
> `export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt `
> Any idea how to do this in openshift also, I mean when we deploy?

Oh, sorry. I missed this one. As discussed on stand up, define an env var in the openshift template:

https://github.com/thoth-station/kebechet/blob/caf3720ef08f8bb548ac0ed61e53b1554d4207c7/openshift/cronJob-template.yaml#L56

> @fridex What certificate should we add when we deploy, would the cron-job, would the image have it and we just point it to it?

The ca-bundle.crt will need to be added as a secret and mounted as a file to the pod:

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-files-from-a-pod

> I think there is `GITLAB_KEBECHET_TOKEN` in job-kebechet-template.yaml, but where do we add, the `GITLABCEE_KEBECHET_TOKEN`?

You can create a new env variable for it.

**Comment by goern** [comment]
@fridex this is more like an architectural discussion, do we need to keep it open? any conclusion?

**Comment by fridex** [comment]
/close

I think we can close this. Let's fully finish github integration first and we can look at gitlab/pagure after that. The repo to be monitored that originally triggered this discussion is not active anymore anyway.
