### ISSUE TITLE
Kebechet update trigger closes issue

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#367]
Creating a new issue with the title - `Kebechet update` or `kebechet update`, should run Kebechet on the repo, and close the issue after the update manager has run successfully on the manager.

As it's event-driven now if we want to update packages on a stale repository, user's should be able to create an issue - 'Kebechet update' and it would be closed when the update manager run's on the repo? 

@fridex wdyt?

**Comment by fridex** [comment]
It would be ok-ish short term. As we release library updates in thoth quite often, it could be too much time for us to check what components need a library update and create an issue for them.

Ideally, we should plug in a kafka trigger that is triggering updates based on the kafka messages so repos get updates based on Thoth's knowledge base (what repositories need an update) CC @KPostOffice on this

BTW it might worth considering creating a prefix or an issue label to distinguish kebechet related issues and reduce the number of workloads (invoke if there is really something to do).

**Comment by saisankargochhayat** [comment]
Currently, the update manager is triggered by push events and all issues. I am going to add a condition to close `Kebechet update` incase it runs successfully. 
 
But its a good idea only to trigger if there a prefix such as - `Kebechet <manager name>`
What would be a good place to check this? Inside the payload parser right? And skip running managers? Btw that would still create the workload. 

I am moving the Kafka idea to a new issue.

**Comment by fridex** [comment]
> But its a good idea only to trigger if there a prefix such as - `Kebechet <manager name>`
> What would be a good place to check this? Inside the payload parser right? And skip running managers? Btw that would still create the workload.

The filtering could be done directly on user-api that would refuse to run the workload.

> Would we change the templates of version releases to have `Kebechet` prefix?

Worth to discuss if we see this beneficial.
