### ISSUE TITLE
Update Manager creates PR's on master repo, not the forked repo.

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#372]
**Describe the bug**
Running the update manager on the forked repo, creates an PR on the master repository rather than on the forked repo. 

Example - https://github.com/saisankargochhayat/clai
Created a PR on - https://github.com/AICoE/clai/pull/1

Seems to be dependent on - https://github.com/packit-service/ogr/issues/307

**Comment by fridex** [comment]
Is there any ogr related change needed to support this?

**Comment by saisankargochhayat** [comment]
> Is there any ogr related change needed to support this?

https://github.com/packit-service/ogr/issues/307
Seems to be dependent on 307, I will try getting it merged soon.
