### ISSUE TITLE
version manager creates `v` tags, and no branch

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#374]
**Is your feature request related to a problem? Please describe.**
right now we create tags `X.Y.Z` the new default should be to create a v-tag like `vX.Y.Z`. In addition to that, we don't need to create a branch for that tag. If we need to do some bugfixes or backporting to a specific tag, we could create the branch at that point in time.

**Describe the solution you'd like**
change version manager

**Describe alternatives you've considered**
n/a

**Additional context**
this would synchronize git tag format and quay image tag format.

**Comment by saisankargochhayat** [comment]
@goern I think this could be closed with - https://github.com/AICoE/Sefkhet-Abwy/pull/27
Or do we need to change Kebechet's behaviour?

**Comment by goern** [comment]
But Kebechet still create a branch based on the tag, doesn't it?

**Comment by saisankargochhayat** [comment]
> But Kebechet still create a branch based on the tag, doesn't it?

It's needed to create the changelog update in source code. And version bump in source code. :smiley:
