### ISSUE TITLE
Kebechet dependency update should not check PyPI but Thoth Knowledge Graph

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#383]
**Describe the bug**
Kebechet updates are not checking Thoth, therefore when the dependency is updated from PyPI and the PR is merged, s2i build using Thoth and only the Pipfile will not find the most updated version of that package just released because it has not been solved yet. Adviser relies on Thoth Knowledge Graph for Solved Python Packages.

Therefore micropipenv will use Adviser suggestions and the build created in test environment won't have the latest version (e.g. graph-sync-job dependency updated when thoth-storages is updated)

**Expected behavior**
Kebechet trusts Thoth, which should have package release job run more often so that graph refresh job can solve those packages faster and therefore having s2i build using Thoth that actually have the latest version (e.g. graph-sync-job would not get the latest thoth-common released until the next day because that is when we run again package release job and after that solver for that package)

**Additional context**
- package release job https://github.com/thoth-station/package-releases-job
- graph refresh job https://github.com/thoth-station/graph-refresh-job

**Comment by fridex** [comment]
Is this related kebechet's thoth-advise manager? If I understand the issue correcly, if we switch to thoth-advise based kebechet manager, this issue will go away as thoth will perform updates only for packages that are analyzed/solved by the system.

CC @KPostOffice

**Comment by goern** [comment]
As Frido's comment seems to be correct, I will close this one, feel free to re-open

/close
