### ISSUE TITLE
handle this exception by opening a feature request

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#39]
The exception at https://github.com/thoth-station/kebechet/blob/dfe1d81bf80f48b9ee2ffe335e3a9705b642030c/kebechet/update.py#L457 could be handled by opening a feature request to add a `Pipfile` or `requirements.in`

**Comment by fridex** [comment]
Kebechet will now open an issue for this with brief instructions how to setup the repo properly. Closing.
