### ISSUE TITLE
Create Grafana dashboard for kebechet metrics

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#408]
Create a dashboard and include it into the slo report

**Comment by pacospace** [comment]
https://github.com/thoth-station/slo-reporter/issues/15

**Comment by pacospace** [comment]
what else do we want to add to slo-report regarding kebechet? I created a panel in SLI/SLO dashboard showing active repo for Kebechet

**Comment by saisankargochhayat** [comment]
> what else do we want to add to slo-report regarding kebechet? I created a panel in SLI/SLO dashboard showing active repo for Kebechet

I think total repos, and delta of total repos in 7 days?

**Comment by pacospace** [comment]
> > what else do we want to add to slo-report regarding kebechet? I created a panel in SLI/SLO dashboard showing active repo for Kebechet
> 
> I think total repos, and delta of total repos in 7 days?

Yes those are received in the email :D

**Comment by fridex** [comment]
Yes, let's close this :+1:
