### ISSUE TITLE
repo does not meet requirements

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#421]
This config uses version manager on the repo, but it looks like the repo does not fulfil the requirements to be version managed...

https://github.com/thoth-station/kebechet/blob/f3935d844566110c3dc4e233cafaab26aa15c192/config/thoth.yaml#L722

**Comment by pacospace** [comment]
The requirement is: https://github.com/thoth-station/kebechet/tree/f3935d844566110c3dc4e233cafaab26aa15c192/kebechet/managers/version#kebechet-version-manager

this repo satisfies that requirement twice:
__init__.py : https://github.com/thoth-station/kebechet/blob/master/kebechet/__init__.py
setup.py: https://github.com/thoth-station/kebechet/blob/master/setup.py

what is the issue?

**Comment by saisankargochhayat** [comment]
I think it was meant for the repo - `thoth-station/datasets`, maybe we can add a `version.py` in the datasets repo? I don't know what the initial version we want for datasets is it 1.0.0?

**Comment by pacospace** [comment]
It should be fixed in https://github.com/thoth-station/datasets/pull/8
