### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#43]
As a user I would like to use Kebechet with GitLab.

1. The configuration of kebechet should provide a github/gitlab switch.
2. All API calls to GitHub have have their GitLab alternatives (see libraries that abstract this).
3. We should support also hosted github - once the config file will be extended, state also API URL of the hosted GitHub instance.

**Comment by fridex** [comment]
Done in #61

**Comment by goern** [comment]
@durandom ;) https://www.youtube.com/watch?v=BAuxMlqkXWc
