### ISSUE TITLE
Automatic update didn't have new hash of package

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#444]
Semver should have new package. 
https://github.com/thoth-station/kebechet/pull/435/files
as pointed out by harshad - https://github.com/thoth-station/slo-reporter/pull/33/files

**Comment by saisankargochhayat** [comment]
Seem's like doing `pipenv install requests==2.24.0 --keep-outdated` for example doesn't work as it used to in Pipenv 2018, the hashes are no more updated and that leads to a wrong Pipfile. 
Related - https://github.com/pypa/pipenv/issues/966

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/kebechet/pull/514

**Comment by fridex** [comment]
I think we can close this. It's an upstream Pipenv issue.
