### ISSUE TITLE
Kebechet docs on thoth-station.ninja

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#461]
**Is your feature request related to a problem? Please describe.**

As a Thoth user, I would like to have a centralized page with how to "first touch Thoth". This documentation should link to all the respective repos for code details.

**Describe the solution you'd like**

Add Kebechet related documentation to:

 https://thoth-station.ninja/docs/developers/adviser/integration.html#kebechet-github-application

**Describe alternatives you've considered**

Keep documentation on a separate page (https://thoth-station.ninja/kebechet/) that does not integrate well with the Thoth application. Also from a maintainability point of view, we have infra to automatically generate docs periodically.

Another alternative is to maintain README file that seems to be "too code centric" for this purpose.

**Additional context**

**Comment by saisankargochhayat** [comment]
Closed using https://github.com/thoth-station/adviser/pull/1501
