### ISSUE TITLE
Kebechet Thamos Advise fails on Srcops-Testing

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#462]
Running thamos-advise manager on [srcops-testing](https://github.com/thoth-station/srcops-testing), the advise manager fails to work. This log was retrieved from `thoth-prod-tensorflow`.
I have put a old package of sourcemanagement in pipfile.lock in srcops-testing, we can test if this creates an update. 

```
 {"message": "An error occurred during run of manager {'configuration': {'labels': ['bot', 'kebechet']}} <class 'kebechet.managers.thoth_advise.thoth_advise.ThothAdviseManager'> for 'thoth-station/srcops-testing', skipping\nTraceback (most recent call last):\n  File \"/home/user/kebechet/config.py\", line 156, in run_url\n    instance.run(**manager_configuration)\n  File \"/home/user/kebechet/managers/thoth_advise/thoth_advise.py\", line 152, in run\n    source_type=ThothAdviserIntegrationEnum.KEBECHET,\n  File \"/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/thamos/lib.py\", line 417, in advise_here\n    requirements_format = thoth_config.requirements_format\n  File \"/home/user/.local/share/virtualenvs/user-5PivF_Od/lib/python3.6/site-packages/thamos/config.py\", line 88, in requirements_format\n    \"No requirements format configuration stated in the configuration file \"\nthamos.exceptions.NoRequirementsFormatError: No requirements format configuration stated in the configuration file under 'requirements_format' configuration entry"}
kebechet-job-2fa8e27a-625046206: {"name": "kebechet.config", "levelname": "INFO", "module": "config", "lineno": 148, "funcname": "run_url", "created": 1593632199.1742487, "asctime": "2020-07-01 19:36:39,174", "msecs": 174.24869537353516, "relative_created": 1848.5946655273438, "process": 1, "message": "Running manager 'info' for 'thoth-station/srcops-testing'"}
```
Complete work-flow log - https://gist.github.com/saisankargochhayat/fa696c335933cdf280f7f1e9e5235c7a

**Comment by pacospace** [comment]
This is expected error as `.thoth.yaml` in the repo does not respect thamos config inputs: https://github.com/thoth-station/thamos/blob/fc737dfd8faf0fe6234ef3356307b7c47051ff6d/thamos/config.py#L86.

**Comment by fridex** [comment]
Can we maintain a schema that verifies the configuration once loaded? It should be fairly easy to construct based on the config file documentation in the thamos repo.

**Comment by saisankargochhayat** [comment]
> Can we maintain a schema that verifies the configuration once loaded? It should be fairly easy to construct based on the config file documentation in the thamos repo.
I was looking how to add it on Kebechet side, and create and issue in case the config file is not correct.

**Comment by fridex** [comment]
> > Can we maintain a schema that verifies the configuration once loaded? It should be fairly easy to construct based on the config file documentation in the thamos repo.
> 
> I was looking how to add it on Kebechet side, and create and issue in case the config file is not correct.
> 
> However after adding the correct config, the advise manager doesn't seem to function as it is supposed to..

The main gate to Thoth backend is user api. Might be good to add the schema to user-api openapi definition. In that case, the config file will be versioned with user-api API version.

**Comment by fridex** [comment]
Resolved by https://github.com/thoth-station/thamos/pull/468 thanks @saisankargochhayat
