### ISSUE TITLE
Create Github releases when releasing in pypi

### ISSUE THREAD

**Issue by 4n4nd** [thoth-station/kebechet#483]
**Is your feature request related to a problem? Please describe.**
releases are created in pypi properly, but it would be great if a release would be created in Github (like [here](https://github.com/AICoE/prometheus-api-client-python/releases)) rather than just a tag.

**Describe the solution you'd like**
Once a pypi release is created, create a release in the github repo.

**Describe alternatives you've considered**
Current alternative is to manually create a release, I think this can be automated.

**Comment by harshad16** [comment]
can you please move this issue to https://github.com/AICoE/aicoe-ci. @4n4nd

**Comment by 4n4nd** [comment]
@harshad16 I don't have permissions in this repo to move an issue :(
Should I just create a new one there?

**Comment by saisankargochhayat** [comment]
This is where we need to add a post request to release api - 
https://github.com/AICoE/sefkhet-abwy/blob/26c1d8903ee6725bd43b13d4d394082736055ea0/aicoe/sesheta/actions/pull_request.py#L416

**Comment by 4n4nd** [comment]
so I should create an issue here: https://github.com/AICoE/sefkhet-abwy ?

**Comment by harshad16** [comment]
> @harshad16 I don't have permissions in this repo to move an issue :(
> Should I just create a new one there?

Thanks for opening the issue.
