### ISSUE TITLE
Report wrong or unhandled run method arguments passed from .thoth.yaml

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#504]
**Is your feature request related to a problem? Please describe.**

Currently, we pass all the arguments to the corresponding `run` method of managers implemented:

https://github.com/thoth-station/kebechet/blob/8e45edee0ac4afefb4fb2b87f7d6ccfebd94e685/kebechet/config.py#L166

Instead of passing all the arguments by expanding the dict (passing expanded kwargs), we should pass directly dict of arguments:

```python
                instance.run(manager_configuration)
```

so that manager instance can pick arguments from the configuration it needs and report wrong arguments present in the configuration option in the respective issue/or by opening a new issue.

**Describe the solution you'd like**

1. pass `manager_configuration` as dict directly
2. each manager should pick respective options from the dict passed
3. each manager should use a common method implemented in kebechet's manager base that reports back any wrong arguments/missing arguments or misspelled arguments

**Describe alternatives you've considered**

Keep the implementation as-is. However it has its drawbacks - if I pass wrong/misspelled configuration entry, kebechet fails. That is not very user friendly.

**Comment by goern** [comment]
/remove-lifecycle stale

this sounds useful!

/sig docs
/kind demo

**Comment by KPostOffice** [comment]
Instead of passing a dict, we could add, `**kwargs` to the end of the run method to catch unused configuration and open issues. I like this approach more because we still will have useful function signatures and type hinting.  WDYT @fridex ?

**Comment by fridex** [comment]
> Instead of passing a dict, we could add, `**kwargs` to the end of the run method to catch unused configuration and open issues. I like this approach more because we still will have useful function signatures and type hinting. WDYT @fridex ?

What if the already present keys in `.thoth.yaml` do not match function signature?

An example could misconfigured `update` manager:

```ytaml
  - name: update 
    configuration:
      labels: [bot]
      someWrongKeyGiven: foo
```

**Comment by KPostOffice** [comment]
This is what I mean.

we load configuration so that we have a dict which looks like:
```
args = {"labels": ["bot"], "someWrongKeyGiven": "foo"}
```
we could have a run command that looks something like this:
```
def run(labels, **kwargs):
    for k in kwargs:
        open_issue_bad_config(k)
    ...
```
and then just call:
`run(**args)`

**Comment by fridex** [comment]
Sounds good 👍🏻
