### ISSUE TITLE
Optimize when managers are run based on webhook

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#507]
**Is your feature request related to a problem? Please describe.**

Kebechet is occupying the backend namespace quite often - each time there is a payload sent. This invocation is correct - kebechet needs to process the given webhook payload. However, it looks like some managers do not need to run - they should be run based on webhook type/payload.

An example can be a "new patch release" issue on github. This issue also triggers other managers (e.g. update manager) which takes too much time for some of the repositories (especially for those that have large dependency graph to be checked).

**Describe the solution you'd like**

Each manager's implementation should state when it should be run.

**Describe alternatives you've considered**

Keep the solution as is - however it is quite expensive when it comes to the number of webhooks we receive.

**Comment by fridex** [comment]
CC @saisankargochhayat

**Comment by saisankargochhayat** [comment]
@fridex Currently the update manager reacts to the following event's - https://github.com/thoth-station/kebechet/blob/25e65d67fb203de017058c6268bc34f07464c3be/kebechet/managers/update/update.py#L62
We can change remove issues or react only to specific issues, but as we don't have a cronjob, some repos would remain with old stack.

**Comment by fridex** [comment]
> We can change remove issues or react only to specific issues, but as we don't have a cronjob, some repos would remain with old stack.

OK, let's implement an internal trigger that would handle "new package release" and let kebechet handle specific issues/events. We need it anyway.

**Comment by goern** [comment]
@fridex is this still valid, or superseded by work @KPostOffice is doing?

**Comment by fridex** [comment]
Still valid. Will depend upon Kevin's work.

/remove-lifecycle stale

**Comment by KPostOffice** [comment]
I think a good way to do this would be adding a function `_should_run()` to each manager which is called prior to running

**Comment by fridex** [comment]
> I think a good way to do this would be adding a function `_should_run()` to each manager which is called prior to running

Might be a good idea to provide information on the class level when the given manager should be run, something like:

```python
class FooManager(ManagerBase):
    """Some example manager."""

    SHOULD_RUN = frozenset({
      NEW_PULL_REQUEST,
      NEW_ISSUE,
      CLOSED_PULL_REQUEST,
    })
```

in that case, the logic behind calling managers will be able to determine when the given manager should be called.

**Comment by KPostOffice** [comment]
I think having function that takes a webhook payload would be better. For example in the case of version manager we don't even want to run for every new issue. We only want to run it if the issue is a very specific format which we might be able to figure out from the payload contents.
