### ISSUE TITLE
auto updates appear twice

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#539]
**Describe the bug**
It seems as auto updates of dependencies are listed twice in the changelog, see https://github.com/thoth-station/advise-reporter/pull/101

**Expected behavior**
they only show up once.

**Additional context**
n/a

/kind bug
/assign @saisankargochhayat 
/project Kebechet

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/advise-reporter/pull/98
https://github.com/thoth-station/advise-reporter/pull/99
Both seem to be PRs from the same branch, only markers are different. Hmm maybe its an issue because the pipfile lock was created using Pipenv 2020
We do catch for already existing prs - https://github.com/thoth-station/kebechet/blob/dfea7b907d1a8baff681bc346235c6c32ec913bf/kebechet/managers/update/update.py#L328

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/advise-reporter/pull/116
https://github.com/thoth-station/advise-reporter/pull/117
I see it again, we could check closed PR's with same branch name and if it exists not create another PR. But fetching closed PR for a large repo, could be slow.

**Comment by fridex** [comment]
> [thoth-station/advise-reporter#116](https://github.com/thoth-station/advise-reporter/pull/116)
> [thoth-station/advise-reporter#117](https://github.com/thoth-station/advise-reporter/pull/117)
> @fridex I m not sure why this is happening, any suggestions?

Nothing from top of my head.

Anyway, do not spend too much time on this. We will essentially throw this part away as we move to thoth based updates.

**Comment by fridex** [comment]
> [thoth-station/advise-reporter#98](https://github.com/thoth-station/advise-reporter/pull/98)
> [thoth-station/advise-reporter#99](https://github.com/thoth-station/advise-reporter/pull/99)
> Both seem to be PRs from the same branch, only markers are different. Hmm maybe its an issue because the pipfile lock was created using Pipenv 2020
> We do catch for already existing prs -
> 
> https://github.com/thoth-station/kebechet/blob/dfea7b907d1a8baff681bc346235c6c32ec913bf/kebechet/managers/update/update.py#L328
> 

Yeah, that might be an issue - different tooling (based on its version) provides different output hence the PR gets opened.

**Comment by saisankargochhayat** [comment]
We can close this now, as we do singular updates.
