### ISSUE TITLE
Provide automated PRs that would update repo from the original template [points?]

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#540]
**Is your feature request related to a problem? Please describe.**
More context - https://github.com/AICoE/aicoe-ci/issues/63

Things to implement for the new manager - 
- [ ] Allow the manager to check for the source of the template using a request like -  `curl -s -H "Accept: application/vnd.github.baptiste-preview+json" https://api.github.com/repos/aicoe-aiops/sync-pipelines`
- [ ] Check the manager config to check what files and folders to sync i.e. it states what folders/files to sync.
- [ ] If the entity is to be synced and out of sync raises an atomic PR syncing the file considering the Template repo as a source of truth. 
- [ ] Add readme about template-sync manager

**Comment by goern** [comment]
@durandom

**Comment by tumido** [comment]
I've been doing this manually for certain repos. Like for this one right now https://github.com/aicoe-aiops/ocp-ci-analysis/pull/31. 

It the automation works in similar way as I did it manually, the first changeset will introduce all the commits in the template history and we don't want users to freak out (since it may be a huge change list).

What we need to keep in mind for that, is that the change will may require manual intervention on the PRs.

**Comment by durandom** [comment]
@saisankargochhayat can you point us to
* where this feature would best fit in the code base
* some similar code (kebechet already create's PRs and probably fetches remote repos)
* a rough pseudo code how it would be implemented

**Comment by fridex** [comment]
> @saisankargochhayat can you point us to
> 
> * where this feature would best fit in the code base
> * some similar code (kebechet already create's PRs and probably fetches remote repos)
> * a rough pseudo code how it would be implemented

Kebechet is made out of "managers" that are called - see https://github.com/thoth-station/kebechet/tree/master/kebechet/managers See this "info" manager as an example https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/info/info.py The entrypoint is "run" method that gets called.

A method called `cloned_repo` can clone a repo for you (the info manager can be a nice example) - https://github.com/thoth-station/kebechet/blob/51bb564b4d2258ad5807b20613a35d46f6914cf7/kebechet/utils.py#L46

**Comment by fridex** [comment]
Once a manager is implemented, it should be registered in the manger listing - https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/__init__.py#L10

Parameters supplied to the "run" method correspond directly to the manager's configuration section in `.thoth.yaml`.

**Comment by fridex** [comment]
Forgot we have docs for this: https://github.com/thoth-station/kebechet/tree/master/kebechet/managers#developing-your-own-manager

**Comment by saisankargochhayat** [comment]
Everything frido mentioned above and good example can be to follow the version manager as it involves changing source code and also closing issues. https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/version

**Comment by codificat** [comment]
It is unclear if this is still relevant now that GitHub has templates at an org level (e.g. https://github.com/thoth-station/.github)

As per today's backlog review, the proposal is to 
/close
this.

If there are reasons to continue working on it please reopen and update
