### ISSUE TITLE
Kebechet update

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#543]

**Comment by pacospace** [comment]
@fridex @harshad16 @saisankargochhayat Kebechet does not update to new glyph released on PyPI :/ See: https://github.com/thoth-station/investigator/issues/231#issuecomment-694508268

**Comment by pacospace** [comment]
> @fridex @harshad16 @saisankargochhayat Kebechet does not update to new glyph released on PyPI :/ See: [thoth-station/investigator#231 (comment)](https://github.com/thoth-station/investigator/issues/231#issuecomment-694508268)

Should I just retry?

**Comment by fridex** [comment]
PyPI is down: https://pypi.org/project/thoth-glyph
![Screenshot_2020-09-18_09-09-42](https://user-images.githubusercontent.com/880687/93567284-b4ab0300-f98e-11ea-81bb-6fa781330340.png)

**Comment by pacospace** [comment]
> PyPI is down: https://pypi.org/project/thoth-glyph
> ![Screenshot_2020-09-18_09-09-42](https://user-images.githubusercontent.com/880687/93567284-b4ab0300-f98e-11ea-81bb-6fa781330340.png)

Thanks I didn't have that two minutes ago :D
