### ISSUE TITLE
Kebechet constantly updating voluptous on adviser repo

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#574]
**Describe the bug**

See PR opened by Kebechet on adviser repo: https://github.com/thoth-station/adviser/pull/1403/

**To Reproduce**
1. Go to thoth-station/adviser
2. Check commit logs https://github.com/thoth-station/adviser/commits/master
3. See multiple updates of voluptous to 0.12.0

**Expected behavior**

The update should happen just once.

**Comment by saisankargochhayat** [comment]
Fixed with https://github.com/thoth-station/adviser/pull/1417
