### ISSUE TITLE
Deployment Doc needs update [3pt]

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#576]
**Describe the bug**
https://github.com/thoth-station/kebechet#deploying-kebechet needs a little update, we use https://github.com/thoth-station/thoth-application/tree/master/kebechet now.

https://thoth-station.ninja/kebechet/how-to-integrate/ needs some update too.

**Comment by saisankargochhayat** [comment]
Added some documentation based on the current implementation. I think the `https://thoth-station.ninja/kebechet/how-to-integrate/` page can be updated after the khebhut app is published and after implementing the authentication part, that would enable us to not force the user to sesheta as a collaborator.
