### ISSUE TITLE
Kebechet should tell humans if they are requesting something not activated

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#577]
**Is your feature request related to a problem? Please describe.**
Kebechet should tell humans if they are requesting something not activated.

**Describe the solution you'd like**
Imagine if a user of Kebechet intalls Kebechet and tries to use a manager which is not activated in its .thoth.yaml.
Kebechet should open PR with .thoth.yaml file updated helping the human.

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
What is an example scenario for this?

**Comment by pacospace** [comment]
> What is an example scenario for this?

Example 1: I have Kebechet installed but didn't add .thoth.yaml, therefore if I ask for `Kebechet update`, Kebechet should open PR with example .thoth.yaml or comment directly in the issue?

Example 2: I have Kebechet installed and .thoth.yaml but only info is present in .thoth.yaml. Now I ask for `Kebechet update` and nothing happens, Kebechet should comments in the issue directly or open a PR with .thoth.yaml to have that manager used as well.

**Comment by fridex** [comment]
Not sure if we want to react to these particularly. `Kebechet update` should go away with internal/external triggers and we should be rather reacting to events happening than to be reacting directly to user requests on the repo (push vs pull design). That way we reduce these errors on the user side and things will be transparent to users.

Let's wait with this until we do not find an example where users would explicitly ask thoth for operations done.

**Comment by KPostOffice** [comment]
I'm not sure I understand the issue. Kebechet only runs based on `.thoth.yaml` configuration. Currently you cannot request to run a specific manager such as `update`.

**Comment by codificat** [comment]
/remove-lifecycle active
still relevant but not a prio
