### ISSUE TITLE
Kebechet assumes the default branch to be master

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#579]
We need to fetch the default branch name and initialize the service class accordingly. The default branch can be found out with maybe - `git symbolic-ref --short HEAD`
https://github.com/thoth-station/kebechet/blob/609735637db076304fbcf8157a51751eb66fdbcd/kebechet/services.py#L60
The cloning logic also should clone default branch -
https://github.com/thoth-station/kebechet/blob/609735637db076304fbcf8157a51751eb66fdbcd/kebechet/utils.py#L59
Also maybe look at other places we default to master.

**Comment by KPostOffice** [comment]
Just took a look into this issue. The suggestion that @saisankargochhayat made should work in most cases, but it does require already having the repository cloned.  In a few places, the branch is used to download files without cloning the whole repository, in these cases there is no way to get the default branch.

**Comment by fridex** [comment]
Maybe we could use GitHub API for this purpose so we don't need to have the repo cloned every time? I can see `"default_branch": "master"` in responses for GH repo API query. I didn't dig into it further, also not sure if GitLab provides such info on endpoints.

**Comment by KPostOffice** [comment]
This was fixed when we switched to ogr. Closing this

**Comment by KPostOffice** [comment]
?
