### ISSUE TITLE
Kebechet can provide context to PR, Issues that are opened from internal trigger

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#584]
As Kebechet user,

I would like to receive context about why Kebechet is opening PR or Issues regarding changes in my software stack.

- [x] Propagate context event trigger in a message sent from Kebechet administrator (https://github.com/thoth-station/workflow-helpers/blob/master/kebechet_administrator.py).
- [x] Define standard context event trigger messages for different cases (new release, CVE, HashMismatch, MissingPackage, MissingVersion) reference: https://github.com/kubernetes/community/blob/master/sig-list.md
- [x] Add context event to message sent to Kebechet administrator. (metadata)
- [x] Make sure latest datetime is used in Kebechet administrator queries but avoid sorting in query for performance issues.
- [x] Extend investigator kebechet run url trigger to propagate context event trigger (https://github.com/thoth-station/investigator/blob/master/thoth/investigator/kebechet_run_url_trigger/investigate_kebechet_run_url_trigger.py)
- [ ] Extend common to propagate the context event trigger (https://github.com/thoth-station/common/blob/a40d96080ae929c512132900842c5dcb4380b97a/thoth/common/openshift.py#L1586)
- [ ] Extend Kebechet run url inputs to have metadata dictionary to handle future metadata that wants to be provided (https://github.com/thoth-station/kebechet/blob/fdeca5d8edddad9d29fde17130bfed5cb36a523f/kebechet/config.py#L103) (all methods in kebechet )
- [ ] the metadata are propagated into adviser metadata
- [ ] `kebechet run results` argo workflow task in adviser workflow should retrieve the context event trigger from adviser document results and open PR or Issue with standardized context.

**Comment by saisankargochhayat** [comment]
Related - https://github.com/thoth-station/investigator/pull/357

**Comment by KPostOffice** [comment]
Depends on: https://github.com/thoth-station/kebechet/issues/696
