### ISSUE TITLE
Pipfile/.lcok links seem broken

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#609]
**Describe the bug**

**To Reproduce**
1. Go to 'https://github.com/thoth-station/user-api/issues/1157'
2. Click on 'Pipfile' link
3. See error

**Expected behavior**
links should be accessible and deliver HTTP:200

**Screenshots**
![image](https://user-images.githubusercontent.com/260331/99967368-107f7700-2d98-11eb-8b78-707b48360258.png)

/kind bug

**Comment by saisankargochhayat** [comment]
https://github.com/thoth-station/user-api/issues/1160
links fixed
