### ISSUE TITLE
Fix URLs to raw files in reports for GitLab

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#64]
Current links in reports (e.g. to Pipfile and Pipfile.lock) work only with GitHub. Reported URLs should also work with GItLab when GitLab is used.

**Comment by fridex** [comment]
@KPostOffice is this still relevant?

**Comment by goern** [comment]
@saisankargochhayat @KPostOffice is this still relevant?

**Comment by saisankargochhayat** [comment]
@goern  Fixed in https://github.com/thoth-station/kebechet/pull/327
