### ISSUE TITLE
Create a pipeline to deploy the label-bot model

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/kebechet#654]
Assumptions:
This is a server deployment. Storage for the model is available in the cluster.
model is in PVC for the deployed pod
Argo/tekton tasks are used for pipeline

- [x] Convert the application into a tornado based API.

- [ ] Add API endpoint for fetching model version, model size , input and output vector etc.
 
- [ ] Figure out to make a PVC with the model data.

- [ ] Deploy the application as an always running API with the model.

- [ ] Create a performance script to test the throughput and latency of the deployed application pod.

- [ ] Document the time taken to load the model, performance values.

- [ ] Add the deployed URL to kebechet argo workflows with the env name - `LABELBOT_URL` in this [file](https://github.com/thoth-station/thoth-application/blob/master/kebechet/base/argo-workflows/kebechet.yaml).
- [x] Add LabelBot Manager to Kebechet to work on new issues. 
- [ ] Activate label bot in repositories by adding to managers in `.thoth.yaml` of the repositories.

Reference - 
Application to Deploy - github.com/thoth-station/Github-Issues-Classifier
Model to download - https://github.com/thoth-station/Github-Issues-Classifier/blob/master/fetch_models.sh

**Comment by saisankargochhayat** [comment]
Make sense, two containers it is - 

- One to fetch the model and mount on a volume
- One container image, just runs the API using this loaded volume
- Finally the pod config to use this shared volume
- Ref - https://www.stratoscale.com/blog/kubernetes/kubernetes-how-to-share-disk-storage-between-containers-in-a-pod/
As per discussion @goern

**Comment by goern** [comment]
There is a project at https://github.com/aicoe-aiops/github-labeler taking over the work

/close
