### ISSUE TITLE
increment version to stable when release candidate is the previous version

### ISSUE THREAD

**Issue by harshad16** [thoth-station/kebechet#657]
**Is your feature request related to a problem? Please describe.**
kebechet version manager, increment version based on the version defined in the controller script(such as __init__.py, version.py,etc). As kebechet gradually increments these versions, the version are always stable.

If a user/developer manually, updates the version field to be a release candidate version(ex: 0.0.1-rc1) 
then the next stable release should be version: 0.0.1 , however currently due to gradual increase the version get updated to 0.0.2

**Describe the solution you'd like**
It would be good if we check for release candidates and such, before making the version update. 

**Describe alternatives you've considered**
manually fixed the version, before making a release request.

**Additional context**
https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/pull/74

**Comment by goern** [comment]
/kind feature
/priority important-longterm

@saisankargochhayat do you want to work on this?
