### ISSUE TITLE
Kebechet should automatically close PR that are no more relevant or outdated

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#659]
**Is your feature request related to a problem? Please describe.**
Some PR opened by Kebechet remain open even when no more relevant: ttps://github.com/thoth-station/storages/pull/2124

**Describe the solution you'd like**
Kebechet should automatically close PR that are no more relevant or outdated

**Describe alternatives you've considered**

**Additional context**

**Comment by fridex** [comment]
If the pull request is outdated, it should be rebased on top of the current master:

https://github.com/thoth-station/kebechet/blob/08a2bd906a5e6617fa2e00b2b0f6d3b66554c10f/kebechet/managers/update/update.py#L311-L316

If the PR is no longer relevant, it should be indeed closed:

https://github.com/thoth-station/kebechet/blob/08a2bd906a5e6617fa2e00b2b0f6d3b66554c10f/kebechet/managers/update/update.py#L752
