### ISSUE TITLE
Kebechet update should point to the PR that update the requirements

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#662]
**Is your feature request related to a problem? Please describe.**
As a user of Kebechet,

when asking for `Kebechet update` I'm currently confused by the message received in the issue: https://github.com/thoth-station/metrics-exporter/issues/555#event-4184141916. 
The message does not show me the information I'm interested in. The PR updating dependencies is opened ( https://github.com/thoth-station/metrics-exporter/pull/556) but not linked to the issue.

**Describe the solution you'd like**
Have link between Kebechet update issue opened and PR open to perform the request of the user.

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
any updates on this?
