### ISSUE TITLE
Changelog generator from repository root commit fails when unrelated histories are present 

### ISSUE THREAD

**Issue by tumido** [thoth-station/kebechet#663]
**Describe the bug**
Kebechet has troubles to generate changelog on release for repositories with unrelated histories, when there's no previous release tag present. This results in a release PR creation failure and the whole release process is halted without a warning.

**To Reproduce**
1. Have a repo and merge an unrelated history from another repo (like merging updates from a parent template repo)
2. Setup AiCoE CI 
3. Create "create release" issue
4. No release PR is created

**Expected behavior**
Either generate release without a changelog (with a warning on the PR), so we have at least the release or fix the root commit resolution. 

**Additional context**
See this comment: https://github.com/aicoe-aiops/mailing-list-analysis-toolkit/issues/18#issuecomment-756821982

cc @harshad16

**Comment by fridex** [comment]
/remove-lifecycle stale

Still relevant.

**Comment by goern** [comment]
@bjoernh2000 maybe while you brows thru the version manager anyways, can you have a look at this?

/priority important-soon
/assign @bjoernh2000

**Comment by bjoernh2000** [comment]
Yes will take a look
