### ISSUE TITLE
[spike] can we maintain mlcube?

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#676]
**Is your feature request related to a problem? Please describe.**
As a Developer on MLCube,
I want to use Kebechet,
so that it helps me publishing new releases,
and so that it keeps the dependencies of MLCube up to date.

**Additional context**
n/a

/kind feature
/assign @fridex 
/assign @pacospace

**Comment by goern** [comment]
I think we need to change the dep mgmt of mlcube a little, but other than that, it looks like kebechet could help.

Let's open PR containing whats required, and add Kebechet to MLCube!

Cc: @sub-mod

**Comment by fridex** [comment]
It looks like they have requirement files in nested directories - they will need to restructure the repo slightly as we do not support them yet (https://github.com/thoth-station/kebechet/issues/20).

**Comment by goern** [comment]
@fridex can you do the restructuring and open a PR? Or do we need Subin to help with that?

**Comment by fridex** [comment]
I can take care of it.

**Comment by goern** [comment]
/unassign @pacospace 
/unassign @fridex 
/triage needs-information

@sub-mod is this something we want to do?

**Comment by goern** [comment]
@sub-mod ping

**Comment by sub-mod** [comment]
I will attend the mlcube meeting and let you know.

**Comment by goern** [comment]
@sub-mod any update on this?
