### ISSUE TITLE
Kebechet feature adoption dashboard

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#679]
**Is your feature request related to a problem? Please describe.**

As a Thoth Product Owner,
I want to have a look at a time series based report
So that I can see the adoption/evolution of Kebechet features.

**Describe alternatives you've considered**
n/a

**Additional context**
This is mainly about reporting/visualizing/dashboarding.

/kind feature
/priority important-longterm
/label sig/slo

**Comment by pacospace** [comment]
Related https://github.com/thoth-station/kebechet/issues/546?
