### ISSUE TITLE
review status of https://github.com/marketplace/qeb-hwt

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#688]
Do we need https://github.com/marketplace/qeb-hwt or is it superseded by https://github.com/marketplace/khebhut

/label question
/sig user-experience
/assign @pacospace 
/sig doc

**Comment by pacospace** [comment]
> Do we need https://github.com/marketplace/qeb-hwt or is it superseded by https://github.com/marketplace/khebhut
> 
> /label question
> /sig user-experience
> /assign @pacospace
> /sig doc

should we move the check run functionality when user open PR to Kebechet?

**Comment by goern** [comment]
and update/planning due to this?
/triage needs-information

**Comment by goern** [comment]
/remove-triage needs-information
/assign
/unassign @pacospace 

I'll de-list Qeb-Hwt from GitHub marketplace
/lifecycle active

**Comment by goern** [comment]
I opened https://support.github.com/ticket/personal/0/1207233 to get this done.

**Comment by goern** [comment]
done.
/close
