### ISSUE TITLE
Provide more infomation on how to fix missing version issues when a new release fails

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#693]
**Is your feature request related to a problem? Please describe.**
See https://github.com/thoth-station/integration-tests/issues/74

I, as a user, would like to know how to fix the linked issue.

**Describe the solution you'd like**

Create a description in the issue body that guides the user to fix the issue.

**Comment by goern** [comment]
/assign @KPostOffice 
could you please have a look at Kevin?

**Comment by KPostOffice** [comment]
Yeah, will do
