### ISSUE TITLE
Misconception in pipfile-requirements manager readme?

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#700]
After reading https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/pipfile_requirements , I deduced that the manager's purpose is keeping `Pipfile`s and `requirements.txt` in sync.

However, the example of manager usage redirects to here https://github.com/thoth-station/kebechet/pull/404 , which is essentialy just an update manager, not a pipfile-requirements manager.

Either i misunderstood the description of `pipfile-requirements` or the example is incorrect.

**Comment by goern** [comment]
/assign @fridex 

I think the example is broken, @xtuchyna could you send a PR to fix it?

**Comment by xtuchyna** [comment]
@goern ofc, but dunno where to find that example of usage

**Comment by xtuchyna** [comment]
this repository prob. does not contain it, I've searched for it but no success.
@fridex should it be under some `Automatic update of...` Issue or is it called differently?

**Comment by xtuchyna** [comment]
I think it probably does not work?
See e.g. commit in `thamos` requirements https://github.com/thoth-station/thamos/commit/65a4869cd4a2f38c9d2ee2d0b1d287cdf0633521#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552
Which indicates @fridex had to manually update. However, the manager is present in thoth-yaml https://github.com/thoth-station/thamos/blob/b7e3ff5d74f5479911405db6fa47319f461bab43/.thoth.yaml#L14

**Comment by fridex** [comment]
This manager was not run for quite some time. But I think investing time to it is not something worth it. It would be better to move this to pre-commit checks or (better) a step in aicoe-ci. These out of sync changes can cause a broken master which should be prevented.

**Comment by xtuchyna** [comment]
Made a new issue for moving the manager elsewhere (#705), therefore closing this one.
