### ISSUE TITLE
Add new entries to the release changelogs in top down/descending order

### ISSUE THREAD

**Issue by LaVLaS** [thoth-station/kebechet#701]
**Is your feature request related to a problem? Please describe.**
When creating new releases, kebechet will update the changelog to include recent commits. These new changes are added to the bottom of the CHANGELOG.md file

**Describe the solution you'd like**
When updating the new changelog, it would be better to add new entries to the top of the file so that anyone reviewing the file will see the most recent changes first.

**Describe alternatives you've considered**
N/A

**Additional context**
See ODH Operator [CHANGELOG.md](https://github.com/opendatahub-io/opendatahub-operator/blob/master/CHANGELOG.md)

**Comment by harshad16** [comment]
/triage accepted 
/lifecycle frozen

This would be worked on with this sprint goal
https://github.com/thoth-station/kebechet/issues/777

**Comment by KPostOffice** [comment]
I believe this was fixed by https://github.com/thoth-station/kebechet/commit/67333054f8f236e18af1a48610687cd9e24dfdcb
