### ISSUE TITLE
Move pipfile-requirements to pre-commit checks

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#705]
**Is your feature request related to a problem? Please describe.**
See #700 
In short: `pipfile-requirements` is currently not used anywhere.

**Describe the solution you'd like**
it is reasonable to move it elsewhere, e.g. to `pre-commit` check.

**Describe alternatives you've considered**
Also consider a better alternative, which would be a step in aicoe-ci.

**Additional context**
See comment by @fridex  https://github.com/thoth-station/kebechet/issues/700#issuecomment-783142061

**Comment by goern** [comment]
@xtuchyna is this still valid?

**Comment by xtuchyna** [comment]
yes, I would say so

**Comment by fridex** [comment]
Something like this should do the trick:

```console
micropipenv requirements --method pipenv --only-direct --no-indexes | sed '/^#/d' | sort > requirements-pipfile.txt
cat requirements.txt | sed '/^#/d' | sort | diff  requirements-pipfile.txt -
```

Not tested, will need some better handling for spaces and better handling of comments, but could be worth to include in AICoE-CI or pre-commit. This can be written in pure Python (micropipenv exposes lib interface).

**Comment by pacospace** [comment]
cc @harshad16

**Comment by goern** [comment]
https://github.com/thoth-station/kebechet/issues/676

**Comment by goern** [comment]
@xtuchyna are you working on this? if so, please lifecycle it, and set a prio

/priority backlog

**Comment by xtuchyna** [comment]
> @xtuchyna are you working on this? if so, please lifecycle it, and set a prio
> 
> /priority backlog

not working on this, not sure whether this issue should stay here or not
