### ISSUE TITLE
When overlays is present and no dependencies are present in root directory Kebechet should not open issue

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#707]
**Is your feature request related to a problem? Please describe.**
When overlays is present and no dependencies are present in root directory Kebechet should not open issue.

**Describe the solution you'd like**
overlays are an alternative to having dependencies in root directory, therefore Kebechet should be hable to differentiate the two cases and act consequently:

- no dependencies in root directory and no overlays -> open issue
- dependencies in root directory and no overlays -> good
- overlays and no dependencies in rott directory -> good

**Describe alternatives you've considered**

**Additional context**
Ref: https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/132

**Comment by KPostOffice** [comment]
@pacospace I feel like the current behaviour makes sense.  `update` manager doesn't support overlays so not having dependencies in the root directory is an issue because it means that it cannot act on the repository.

**Comment by pacospace** [comment]
> @pacospace I feel like the current behaviour makes sense. `update` manager doesn't support overlays so not having dependencies in the root directory is an issue because it means that it cannot act on the repository.

I agree, this should be a feature request rather than a bug indeed :)
