### ISSUE TITLE
Suggestion: Release a new version after PR merges

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#711]
**Is your feature request related to a problem? Please describe.**
I often find myself releasing new patch releases right after some PR merges, and therefore I have to constantly check if the PR was merged and whether it's the right time to release or not.

**Describe the solution you'd like**
For example, having an Issue template New patch release after merged PR <id> would automate this :zap: 

**Describe alternatives you've considered**
Or maybe having some checkbox option in PR like:

- [ ] Release a patch version

that when checked, a new release is made after merge

**Comment by xtuchyna** [comment]
should I make this into user story and all that stuff?

**Comment by goern** [comment]
> should I make this into user story and all that stuff?

ja, if you want to get this implemented, you should!

**Comment by xtuchyna** [comment]
TODO: create an intern project out of this
https://github.com/thoth-station/core/tree/master/docs/intern-projects

as was discussed on tech talk session at https://docs.google.com/document/d/1XmXYEWEwgOBHqdJkUTmhBvUb41pr5GIR2pePasvvZ1s/edit#heading=h.ojm5k4h8h15f

/assign @xtuchyna

**Comment by goern** [comment]
what is the status of this issue?

**Comment by goern** [comment]
/remove-lifecycle rotten
/reopen

@xtuchyna any update on this?

**Comment by KPostOffice** [comment]
Hey @xtuchyna I implemented this in https://github.com/thoth-station/kebechet/pull/877. Sorry I didn't realize it had been turned into an intern project
