### ISSUE TITLE
Kebechet managers support overlays

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#715]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/thoth-station/kebechet/issues/707

**Describe the solution you'd like**
Kebechet managers support overlays and provide updates to all stacks.

**Describe alternatives you've considered**

**Additional context**

**Comment by goern** [comment]
@KPostOffice @pacospace please push this forward! :)

**Comment by KPostOffice** [comment]
I demoed this on Monday

/close
