### ISSUE TITLE
Uninstall unused libraries

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/kebechet#727]
**Is your feature request related to a problem? Please describe.**
Sometimes libraries are not removed all at once or are only used in one spot which is then refactored. Even though the library is no longer used it may still be present in `Pipfile` or `requirements.txt`.

**Describe the solution you'd like**
I would like a Kebechet manager which checks library usage to make sure that all the packages defined in my requirements are being used. If they aren't it should uninstall/remove the libraries which are unused from requirements files.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> Sometimes libraries are not removed all at once or are only used in one spot which is then refactored. Even though the library is no longer used it may still be present in `Pipfile` or `requirements.txt`.
> 
> **Describe the solution you'd like**
> I would like a Kebechet manager which checks library usage to make sure that all the packages defined in my requirements are being used. If they aren't it should uninstall/remove the libraries which are unused from requirements files.

This can be a nice follow up for the summer project the intern will work on @goern @fridex

**Comment by goern** [comment]
I would rather say: create a container image that fits exactly? removing rpm feels like a dangerous operation... but... fork it out as an issue and lets triage/needs-info on it ;)

**Comment by goern** [comment]
We agreed that this manage would only remove Python Modules from Pipfile and relock/advise, and not remove low-level libraries or RPM. 

/remove-triage needs-information

**Comment by goern** [comment]
what is the status of this issue?

**Comment by pacospace** [comment]
> what is the status of this issue?

Tlegen is working on it, but there are other tasks to be finished before having this one.

**Comment by tlegen-k** [comment]
label/work-in-progress
Related PR #775

**Comment by goern** [comment]
/close
feel free to reopen this!
