### ISSUE TITLE
prepend changes instead of appending them

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#736]
https://github.com/thoth-station/kebechet/blob/8b37b5edd969a6ca875735a2de32c5afec4b121d/kebechet/managers/version/version.py#L302

/kind feature
/kind demo
/label "good first issue"
/assign @bjoernh2000

**Comment by bjoernh2000** [comment]
resolved in #744

**Comment by fridex** [comment]
> resolved in #744

Nice, thanks!

BTW you can add "fixes" or [other keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to the pull request to close the corresponding issue.

/close
