### ISSUE TITLE
Extend Kebechet Image with support of python 3.7,3.9 

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/kebechet#800]
**Describe the bug**
https://github.com/thoth-station/solver/issues/1618

**Expected behavior**
We should either document that Kebechet update manager does not work with Py3.7 or make sure that we have more Python versions available in the Kebechet container image

**Steps**
- [ ] add Py3.7 to Kebechet Docker file
- [x] add Py3.9 to Kebechet Docker file

**Comment by codificat** [comment]
Fedora 31 being EOL (where Python 3.7 requirement came from) there's no need to add it.

/close
