### ISSUE TITLE
Kebechet is doing nothing...

### ISSUE THREAD

**Issue by qJJt7oxN** [thoth-station/kebechet#802]
**Describe the bug**
I (goern) installed Kebechet yesterday, and it didnt do anything on https://github.com/qJJt7oxN/python-docs-hello-world 

**To Reproduce**
1. Go to https://github.com/qJJt7oxN/python-docs-hello-world
2. Click on 'Pull Requests'
3. See no PR or Issue by Kebechet

**Expected behavior**
something

**Comment by pacospace** [comment]
Is it because right now zero cluster is not working?

- [ ] Identify what do we expect from Kebechet once installed.

**Comment by KPostOffice** [comment]
Also related: #797, #803 
Without some configuration Kebechet will not run any managers.

**Comment by goern** [comment]
I added https://github.com/qJJt7oxN/python-docs-hello-world/commit/3343d9f598d4a61e83c981f9fe07f35171e40aa7

**Comment by goern** [comment]
I actually removed that sesheta is assigned to issues created by version manager...

**Comment by pacospace** [comment]
> I actually removed that sesheta is assigned to issues created by version manager...

maybe Khebut needs to activate them when installed, see https://github.com/thoth-station/kebechet/issues/794#issuecomment-910265258

**Comment by KPostOffice** [comment]
This workflow should be tested again:
`new_user`->`new_repo`->`fresh kebechet install`
Make sure that Kebechet is behaving as expected.
Acceptance criteria:
- [ ] When new Keb is installed, and no configuration is found Kebechet will open issue with basic configuration
- [ ] Enable update or advise manager and create an issue manually for updating and make sure that eventually Kebechet updates the issue contents as it acts on it

**Comment by KPostOffice** [comment]
I did this with my own new repository and didn't see anything happening:
https://github.com/temposto/my_initial_repo

Might be an issue with installation
