### ISSUE TITLE
Kebechet thoth-advise should support also requirements.txt as stated in docs

### ISSUE THREAD

**Issue by pacospace** [thoth-station/kebechet#805]
**Describe the bug**
See: https://github.com/qJJt7oxN/python-docs-hello-world/issues/2 and Kebechet docs: https://github.com/thoth-station/kebechet#kebechet

**To Reproduce**
1. Have a repo with Khebut installed
2. Have a repo with thoth-advise enabled and only requirements.txt

**Expected behavior**
thoth-advise manager is able to handle also requirements.txt

**Screenshots**

**Additional context**
Only Pipfile logic is present: https://github.com/thoth-station/kebechet/blob/36cd50150d6f482168486c87efdc7491cb06dc67/kebechet/managers/thoth_advise/thoth_advise.py#L217

but also logic for requirements.txt should be present as in thamos: https://github.com/thoth-station/thamos/blob/8ad0e2fdbde0a2775db6745969738a4b19873d36/thamos/lib.py#L640

**Comment by KPostOffice** [comment]
This was actually fixed by https://github.com/thoth-station/kebechet/commit/7f325bd64fd4202fc637af6ccccab00860cb418f

**Comment by pacospace** [comment]
> This was actually fixed by [7f325bd](https://github.com/thoth-station/kebechet/commit/7f325bd64fd4202fc637af6ccccab00860cb418f)

Sorry @KPostOffice where is the logic handling requirements.txt in thoth-advise?
