### ISSUE TITLE
Missing context in support issues created from exceptions

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#814]
**Describe the bug**

Support issues created by Kebechet when one of its managers hits an exception do not contain information about the source repo.

This can make it hard to solve some of them.

**To Reproduce**

1. Encounter a situation where a Kebechet manager throws an exception
2. Kebechet opens an issue in the support repo
3. See the created issue

**Expected behavior**

Context information (e.g. which repo is this affecting) should be present in the support issue created by kebechet.

Also, some exceptions might be handled differently, directly on Kebechet, e.g. to open a user friendly issue if the exception might be related to a repo misconfiguration

**Screenshots**

See thoth-station/support#20 for an example

**Additional context**

These issues were previously created on the repos that Kebechet was working on, but with #810 they are now created in the support repo.

**Comment by KPostOffice** [comment]
@codificat I have added the link to the responsible repository, is there anything else which should be added

**Comment by codificat** [comment]
Thanks @KPostOffice. The link to the originating repo it should be enough for now, so let's
/close
this one. We can open separate issues for more fine tuned exception handling, per exception type (e.g. handle ConnectionError)
