### ISSUE TITLE
Explicitly perform lock if the given package was not found in the lock

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#82]
If kebechet cannot find a dependency in the locked down stack, it should explicitly perform locking so that dependencies in the lock files get updated.

**Comment by goern** [comment]
is this still relevant?

**Comment by fridex** [comment]
Yes.

**Comment by saisankargochhayat** [comment]
@fridex Should I close this?

**Comment by fridex** [comment]
> @fridex Should I close this?

Yup, go ahead :+1:
