### ISSUE TITLE
New manager handling automatic releases

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#847]
**Is your feature request related to a problem? Please describe.**
As discussed on the tech talk:

As a user of Thoth, I would like to be able to configure Kebechet to automatically create new releases. For this, I would like to utilize labels on GitHub - if a user or bot adds a label to a pull request (ex. "release-on-merge") Kebechet will create an issue "New * release" (based on configuration).

**Describe the solution you'd like**

Implement a new manager that can handle new releases based on labels on merged PRs.

**Describe alternatives you've considered**

Move this logic to AICoE-CI, but it looks like Kebechet is the right place to do it as we reuse the whole architecture.

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/kebechet/pull/877
