### ISSUE TITLE
Extend issue body when opening pull-requests with configuration

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#848]
**Is your feature request related to a problem? Please describe.**
As discussed on the tech talk:

I, as a user of Kebechet, would like to have information on how to configure Kebechet on my repository. The body of PRs could be extended to guide users on how to properly configure Kebechet.

References: https://docs.google.com/document/d/1XmXYEWEwgOBHqdJkUTmhBvUb41pr5GIR2pePasvvZ1s/edit#

**Comment by goern** [comment]
@KPostOffice any update on this?!
