### ISSUE TITLE
Automatically raised Key error for 'src' Pipfile.lock member not having 'version' key in package_info dictionary.

### ISSUE THREAD

**Issue by JamesKunstle** [thoth-station/kebechet#860]
**Describe the bug**
Following up on this issue: https://github.com/sandiego-rh/sandiego/issues/36
Kebechet threw a runtime exception when running the '_get_all_packages_versions()' function as a part of an automated task. I tracked the issue back to the likeliest inclusion in our Pipfile.lock, being for 'src'. Reading the issue from our project, you'll see the link.

**To Reproduce**
Exception was thrown in an automated process.

**Expected behavior**
Would have expected this exception not to be thrown for a potentially well-known inclusion in Pipefile.lock (could be a novel inclusion but we generated our Pipfile.lock via standard pipenv workflow.

**Screenshots**
Issue reflects needed context.

**Additional context**
None.

**Comment by goern** [comment]
any update on this?

**Comment by KPostOffice** [comment]
I think this was solved by https://github.com/thoth-station/kebechet/commit/0cc12741cad6e5c2611487b0f4518b3c35578747 an issue should be opened on the repository in the case of a local installation
