### ISSUE TITLE
Unrelated commit in Kebechet update issue

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#875]
**Describe the bug**
After requesting kebechet for an update, it says that the issue is no longer relevant and references unrelated commit
See https://github.com/thoth-station/mi/issues/472

**Expected behavior**
Should reference commit in related PR, which is https://github.com/thoth-station/mi/pull/473

/kind bug

**Comment by KPostOffice** [comment]
This issue is ifixed, the message will only occur if the dependencies are up to date. Though it could do with a better message.
