### ISSUE TITLE
Lookup of mainainers within the OWNERS file apparently references an invalid key

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#876]
**Describe the bug**

The lookup of maintainers here:
https://github.com/thoth-station/kebechet/blob/v1.5.5/kebechet/managers/version/version.py#L198

seems to reference a `maintainers` section within the `OWNERS` file. However, the [spec for this file](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners) does not include such a section.

**To Reproduce**

I have not attempted to reproduce this yet, only found this while reviewing code... maybe I missed something?

Will try to reproduce.

**Expected behavior**

We should probably look at the `approvers` section of `OWNERS`.

This might get a bit more complex if aliases/groups are used there.

**Additional context**

Note: the [example in the readme](https://github.com/thoth-station/kebechet/blob/master/kebechet/managers/version/README.rst#example) says, about maintainers configuration:

> This configuration is optional and you can provide OWNERS YAML file in your repository with the same configuration

**Comment by goern** [comment]
I think maintainers is something found in .thoth.yaml and the version plugin coding section of it? @fridex
