### ISSUE TITLE
extend issues created by kebechet to carry more information

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#887]
**Is your feature request related to a problem? Please describe.**
Looking at https://github.com/thoth-station/s2i-minimal-notebook/issues/295 it is unclear which version of what manager created the issue, some more information being visible on the issue itself are helpful.

**Describe the solution you'd like**
a kebechet version info details-section

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.** Looking at [thoth-station/s2i-minimal-notebook#295](https://github.com/thoth-station/s2i-minimal-notebook/issues/295) it is unclear which version of what manager created the issue, some more information being visible on the issue itself are helpful.
> 
> **Describe the solution you'd like** a kebechet version info details-section
> 
> **Describe alternatives you've considered** n/a
> 
> **Additional context** n/a

It is actually in the environment details of the issue:

```
Kebechet version: 1.5.5
Python version: 3.8.6
Platform: Linux-4.18.0-305.19.1.el8_4.x86_64-x86_64-with-glibc2.2.5
pipenv version: pipenv, version 2020.11.15
```

and that issue should be related to missing py3.9 in Kebechet: https://github.com/thoth-station/kebechet/pull/883

**Comment by codificat** [comment]
> It is actually in the `environment details` section of the issue:

Right, kebechet version is there.

> **Describe the solution you'd like**
> a kebechet version info details-section

@goern: other than version information, is there any additional information that should be added?
/sig user-experience

**Comment by goern** [comment]
let's start with the version...
