### ISSUE TITLE
have update/adivse manager create comments on issues (if triggered by issues)

### ISSUE THREAD

**Issue by goern** [thoth-station/kebechet#891]
**Is your feature request related to a problem? Please describe.**
see https://github.com/thoth-station/ps-ip/issues/15 the user feels a little left alone if kebechet is not commenting on this kind of issues.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
TBD

/priority important-soon

Cc: @pacospace @EldritchJS

**Comment by pacospace** [comment]
Related-to: https://github.com/thoth-station/kebechet/issues/872

**Comment by goern** [comment]
d'uh :) didnt see that :/

**Comment by codificat** [comment]
> Related-to: #872

more than related, it seems
/triage duplicate
/close
