### ISSUE TITLE
Secrets in logs

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#911]
**Describe the bug**

It looks like the following log message keeps secret in logs:

```
2021-11-16 19:18:11,139   1 INFO     kebechet.utils:58:
```

**To Reproduce**
Steps to reproduce the behavior (see discussion in https://github.com/thoth-station/invectio/issues/122):
1. Create an issue requesting a new release
2. Check kebechet logs
3. See secret exposed in logs

**Expected behavior**

Secrets should not be present in logs.

**Comment by harshad16** [comment]
Fixed with https://github.com/thoth-station/kebechet/pull/909
