### ISSUE TITLE
Build versions don't work for container images

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#925]
**Describe the bug**

The format of the build versions, like `1.0.1+build.1`, is not acceptable as a container image tag.

This prevents building container images directly from a version of that kind.

**To Reproduce**

1. Go to a repo with kebechet version manager enabled
2. Create an issue "New build release"
3. Wait for the PR with the version update to merge
4. See that the resulting version ends with `+build.X`.
5. Verify that a container image can not be directly built using the tag from that version

**Expected behavior**

A new version of the container image can be built straight from the build release tag.

**Screenshots**

An example of this is https://github.com/thoth-station/integration-tests/issues/220 where a new build version was tagged as `kebechet-v0.8.5+build.1` (side note: the _kebechet-_ prefix in that tag is a different bug, #921, already fixed but not yet in prod).

The subsequent pipeline run to build the image failed, with this in the logs for tag-release:

```
step-build
+ buildah bud --storage-driver=overlay --tls-verify=false --layers -f /gen-source/Containerfile -t integration-tests-kebechet-v0.8.5+build.1 .
tag integration-tests-kebechet-v0.8.5+build.1: invalid reference format
```

**Comment by harshad16** [comment]
/triage accepted

1. Python packaging supports unique characters like `+`.
2. semver standard also follows https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions
3.  Docker tag naming convention doesn't follow `+`.

solution:
Build pipeline patching the `+` to `-`.
