### ISSUE TITLE
Documentation for Kebechet is not available

### ISSUE THREAD

**Issue by codificat** [thoth-station/kebechet#944]
**Describe the bug**

The documentation for Kebechet can not be found online due to some broken references.

**To Reproduce**
1. Go to https://github.com/thoth-station/kebechet/blob/a0b49c64524d2b8465506165c6d4c95c07f51472/README.rst
2. Click on the link under "Full documentation", which points to https://thoth-station.ninja/docs/developers/kebechet
3. Get a `404 Not Found`

Also:
1. Go to the thoth-station.ninja website
2. Navigate through the docs to https://thoth-station.ninja/docs/developers/adviser/integration.html#kebechet-github-application
3. Follow the link to the managers doc: https://github.com/thoth-station/kebechet/tree/master/kebechet/managers
4. Individual links to managers in [the readme](https://github.com/thoth-station/kebechet/blob/a0b49c64524d2b8465506165c6d4c95c07f51472/kebechet/managers/README.rst) are broken

**Expected behavior**

Docs should be easy to find and free from broken links

**Additional context**

See #850 for a recent docs restructure

**Comment by fridex** [comment]
Might be related: https://github.com/thoth-station/nepthys/issues/80
