### ISSUE TITLE
Point users to use thamos instead of pipenv

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#945]
**Is your feature request related to a problem? Please describe.**

See for example https://github.com/thoth-station/aicoe-ci-pulp-upload-example/issues/20#issue-1086102656. It would be great if Kebechet suggests to use thamos CLI to create requirements file.

**Describe the solution you'd like**

Replace Pipenv references with thamos instructions.

**Comment by KPostOffice** [comment]
Should we point to both `pipenv` and `thamos` as resolution engines or should we just put thamos?

**Comment by fridex** [comment]
> @fridex should we point to both `pipenv` and `thamos` as resolution engines or should we just put thamos?

thamos preferably - that's something we would like to support
