### ISSUE TITLE
Start using PyPI for releases

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#95]
Currently, we install Kebechet directly from source repo that causes sometimes failures - as containers are cached, we sometimes end up with old code in container. We should start do proper releases (now with version manager, that should be transparent) and trigger OpenShift generic trigger to build based on PyPI release.

**Comment by goern** [comment]
1. ja
2. cached containers sounds like an operational issue, any further hints?!

**Comment by fridex** [comment]
A workaround might be:

```yaml
noCache: true
```

as we will not pin down kebechet version and always go with latest (that is triggered on new PyPI release):

**Comment by goern** [comment]
can this be closed?

**Comment by goern** [comment]
ping

**Comment by fridex** [comment]
Yes, let's close it as we will use "active kebechet".
