### ISSUE TITLE
New version of Kebechet warns about missing git tags

### ISSUE THREAD

**Issue by fridex** [thoth-station/kebechet#987]
**Describe the bug**

See recent releases, such as https://github.com/thoth-station/storages/pull/2551 It looks like Kebechet warns about missing last version tag even though a previous version is available.

**To Reproduce**
1. Try to create a new release
2. See the warning message produced
  
  ```
WARNING NOTE
The release version mentioned in the source-code couldn't be found in git tags, hence the release is created from the start.
If that is not the right behavior:```

**Expected behavior**

No warning note should be shown.

**Comment by KPostOffice** [comment]
@fridex this looks like it must be an issue with whatever check adds this warning to the issue, as the changelog and version file seem to be handled fine. I will look into this really quickly. Expecting a quick fix.

/assign @KPostOffice
