### ISSUE TITLE
Automatically update the base image version for new container images

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/kebechet#991]
**Is your feature request related to a problem? Please describe.**
We would like to have an automatic update of the base image used to build our container images to the latest version available on Quay. See: 
- https://github.com/thoth-station/thoth-application/pull/2314#issuecomment-1029721353
- https://github.com/thoth-station/user-api/pull/1657

**Describe the solution you'd like**
Implement a new manager to update automatically the base image version based on what is available on Quay (see: https://github.com/thoth-station/kebechet/issues/847 for a similar example). This could be implemented as part of Kebechet or as a new service.

Or: add a Tekton event listener to trigger the update when a new version of the base image is released.

**Describe alternatives you've considered**
Do the change manually.

**Comment by codificat** [comment]
Is this a duplicate of https://github.com/thoth-station/core/issues/359?

**Comment by goern** [comment]
> Is this a duplicate of https://github.com/thoth-station/core/issues/359?

Ja! You found it, I was not able to find it :/

**Comment by mayaCostantini** [comment]
/close
Duplicate (subset) of https://github.com/thoth-station/core/issues/359

**Comment by fridex** [comment]
> /close Duplicate (subset) of [thoth-station/core#359](https://github.com/thoth-station/core/issues/359)

I think we could rethink this a bit. The referenced issue talks about bumping the base image used in `.aicoe-ci.yaml` - like in https://github.com/thoth-station/user-api/pull/1657/ I think that is one use case we could implement as discussed in the referenced issue.

Another one could be about automatic bumps in thoth-application - like in https://github.com/thoth-station/thoth-application/pull/2316 This could be a different implementation that would automatically open pull requests based on built container images (it can be a standalone cronjob or part of aicoe-ci.yaml configuration and let AICoE-CI open pull requests once container images are built). During the release cycle, we could just `/approve` whatever we see should be populated to the stage environment and eventually prod (if we do not want to keep bulk bumps as done in https://github.com/thoth-station/thoth-application/commit/afff34f1f3cf1f152a0adcb7cd129b53cc3e7f2b, worth discussing). Anyway, this would automate propagating container images to environments (at least stage) and would reduce anoying burden to open "Bump `<component> ` to version `<version>` to stage" and the need for checking if built container images are available as in https://github.com/thoth-station/thoth-application/pull/2313#issuecomment-1029106902 (prone to errors).

**Comment by fridex** [comment]
Let's talk about this on the next tech talk. Until then,

/reopen

**Comment by harshad16** [comment]
Action Items:

- [ ] Discuss in the ADR on core repo about the solution.
- [ ] Proposed plan based on "Lets talk Thoth" calls was to have a separate script:
   - [ ]  Develop a python script to bump base image in pipeline-helper [repo](https://github.com/thoth-station/pipeline-helpers).
   - [ ] Have the script modular, let it take input file (ex: .aicoe-ci.yaml, .thoth.yaml) and bump base image based on the input file.

Building block for bump image:

```
Block 1:
push event choice repo , 
input file, cloned repo 

Block 2
the script receives the input file, cloned repo
API to quay for checking the latest version
Verison Bump  

Block3 
open pr and some detail in pr description 
```

Useful resources:
https://docs.quay.io/api/swagger/ 
https://github.com/AICoE/aicoe-ci

Event Trigger:
- should we have it triggered by quay API? 
- should we have it triggered by GitHub webhook on push event(only on active repos)?

**Comment by mayaCostantini** [comment]
/close
Closed by: https://github.com/AICoE/aicoe-ci/pull/170, https://github.com/thoth-station/pipeline-helpers/pull/45, https://github.com/thoth-station/core/pull/381
