### ISSUE TITLE
Kebechet does not merge approved PRs in `mi` repository

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/kebechet#997]
**Describe the bug**
E.g. look here https://github.com/thoth-station/mi/pull/514

/kind bug

**Comment by xtuchyna** [comment]
another one: https://github.com/thoth-station/mi/pull/517

**Comment by pacospace** [comment]
> **Describe the bug** E.g. look here [thoth-station/mi#514](https://github.com/thoth-station/mi/pull/514)
> 
> /kind bug

This one was merged actually :)

**Comment by xtuchyna** [comment]
> > **Describe the bug** E.g. look here [thoth-station/mi#514](https://github.com/thoth-station/mi/pull/514)
> > /kind bug
> 
> This one was merged actually :)

 2 minutes ago :tongue:
had been stale for 22hrs

**Comment by KPostOffice** [comment]
@xtuchyna Kebechet is not in charge of these merges. It is covered by https://github.com/AICoE/sefkhet-abwy

**Comment by goern** [comment]
any updates on this? do we consider it done?
